### ISSUE TITLE
Ako používateľ chcem vidieť čo všetko budem musieť robiť pri danej životnej situácii

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#11]
- Ako úvodný text by som mal vidieť naľavo procesné kroky a napravo nejaký všeobecný popis. _toto treba zachytiť v štatistikách_
- Budem sa vedieť preklikávať medzi jednotlivými procesnými krokmi. Mala by sa meniť URL, aby som vedel na konkrétny krok niekoho odnavigovať.

**Comment by eronisko** [comment]
Toto je podla mna hotovo -- prve je zachytene v dizajne a druhe v DB (`slug` stlpce)
