### ISSUE TITLE
Mobilná verzia

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#110]

**Comment by jsuchal** [comment]
Toto podla mna kym pojdeme von public by sme mohli dat. Co ty na to @filiplikavcan ? Nevyzera, ze tam bude tak strasne vela prace ako to vyzeralo na zaciatku.

**Comment by filiplikavcan** [comment]
Ano, je tam len par veci, ktore treba doladit.

**Comment by jsuchal** [comment]
Zapracovane v novom flow.
