### ISSUE TITLE
aplikacia: Odklad danoveho priznania

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#112]
vzor https://cdn.webnoviny.sk/sites/20/2016/03/tlacivo-ziadost-o-odklad-danoveho-priznania-fyzicke-osoby.pdf

rozdielne tlacivo pre fyzicke a pravnicke osoby

**Comment by jsuchal** [comment]
@PetraPlesnikova mame toto v trello? Obsahove veci by sme mali presunut tam.
