### ISSUE TITLE
stavovy flow

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#118]
Prepina sa niekedy stav do waiting?
V takejto situacii by to davalo zmysel: mam hotovy prvy krok a caka sa, kym budem moct odkliknut dalsi. 
Uloha by mala byt v modrom waiting stave. 

![targetprocess-screen-capture 6](https://user-images.githubusercontent.com/45393631/53798305-45022e00-3f38-11e9-9503-f946d39d1516.png)

**Comment by HanaBene** [comment]
resp. podam ziadost o obciansky, ako oznacim, ze som ho dostal? Prepinanie v zozname uloh je neintuitivne.

**Comment by jsuchal** [comment]
Fixnute v novom flowe.
