### ISSUE TITLE
Podporte nas (vo footeri) otvorit v novom okne

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#119]

**Comment by tomas-radic** [comment]
Submitol som pull request na tuto poziadavku.

**Comment by jsuchal** [comment]
@tomas-radic dobre to je, ale ak mozes davat do comit nieco ako `closes #119` alebo `fixes #119` nech to hned zavrie potom ked to mergneme.

**Comment by tomas-radic** [comment]
@jsuchal ok.
