### ISSUE TITLE
Ako používateľ chcem začať/spustiť návod

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#12]
- Keď kliknem na spustenie návodu (vľavo hore) alebo pri úvodnom texte (vpravo) by mal byť button "začať".
- Toto si len vypýta email a na pošle tam custom URL, ktorú bude môcť užívateľ používať a presmeruje na túto custom URL, napr.: /moje-zivotne-situacie/xyzabc
- Táto URL by sa nemala dať zobraziť len tak, je potrbné aby sa browser/email spároval a.k.a magic link + login cookie. Login sa deje cez magic link do emailu (ako napr. slack). Nice to have: alternatívne SSO cez FB/Google _Toto je na zvazenie ci SSO nebude lahsie, avsak magic link ide vsetkym co maju email hocikde a registracia je seamless._
- Následne je užívateľ presmerovaný na prvý krok návodu.

**Comment by jsuchal** [comment]
Po burlivej diskusii s @MiroBabic teda ideme stylom SSO (google mozno fb) + magic link. Obe moznosti.

**Comment by eronisko** [comment]
Toto je hotovo
