### ISSUE TITLE
Link na Ochranu osobnych udajov vo footri je prazdny

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#120]
![capture](https://user-images.githubusercontent.com/45393631/53814948-f321ce00-3f60-11e9-9de5-63bcd2563ae1.PNG)

treba spravit page ochrana osobnych, skopirujeme z https://slovensko.digital/ochrana-osobnych-udajov ? @jsuchal

**Comment by jsuchal** [comment]
@HanaBene linky su hotove cize mozes to tam skopcit.

**Comment by HanaBene** [comment]
pridala som text zo slovensko.digital, 
zatvaram.
