### ISSUE TITLE
Ako pouzivatel chcem zmazat konto

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#127]
Ako pouzivatel by som mal vediet zmazat svoje konto, idealne niekde v profile cez confirm (aby to niekto nespravil nahodou).

**Comment by michal-rohacek** [comment]
Chceme tiez zvazit poslanie confirmation emailu pred zmazanim uctu.

**Comment by maftvej** [comment]
Toto by som si zobral ja
