### ISSUE TITLE
Ako používateľ chcem označiť nejaký krok ako hotový (resp. zmeniť stav)

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#13]
- Po kliknutí na procesný krok vľavom menu (ikonu) môžem zmeniť stav na ukončená/rozpracovaná/čaká sa na odpoveď (_Tu mozno rozlisit este aj cakanie a presiahnutie lehoty._)/nezačatá. Ak zmením stav na hotové, som automaticky presmerovaný na ďalší procesný krok.
- Ak zmením stav na čaká sa na odpoveď, mal by som vidieť kedy by som mal dostať odpoveď (resp. odkedy beží lehota). Pozor wireframe:
![unnamed 1](https://user-images.githubusercontent.com/45393631/49230952-25b3ac00-f3f1-11e8-88ed-d50cb795ac6a.png)

**Comment by eronisko** [comment]
Oznacenie kroku ako hotoveho hotoveho. Da sa bud odskrtanim vsetkych poduloh, alebo klikom na timeline.

**Comment by eronisko** [comment]
Ostavaju dalsie stavy

**Comment by jsuchal** [comment]
@tomas-radic toto je asi hotovo nie?

**Comment by tomas-radic** [comment]
Ano.

**Comment by jsuchal** [comment]
Waiting stav sa riesi inde, toto zatvaram.
