### ISSUE TITLE
Ako používateľ chcem označiť najaký podkrok ako hotový (resp. zmeniť stav)

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#14]
- tieto kroky sú true/false
- keď označím všetky ako hotové, mal by byť nadradený procesný krok označený ako hotový (resp. podľa kontextu, napr.: čakanie na odpoveď) Ak sa neočakáva žiadna ďalšia interakcia, nadradený krok sa označí ako hotový.

**Comment by eronisko** [comment]
Toto je hotove
