### ISSUE TITLE
Navod Eurovolby doriesit flow

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#144]
tento navod nema kroky, ide  len o infromacie a pride tam aplikacia na poziadanie o hlasovaci listok.
ked kliknem na zacat vybavovat, napise mi ze Hotovo! vybavene, parada. pri tom som este nezacala citat.
mozne riesenia:
- button prec
- pridat kroky
- nejake ine riesenie vymysliet

**Comment by eronisko** [comment]
@jsuchal @HanaBene toto este plati?

**Comment by HanaBene** [comment]
ano - ale budu to volby vseobecne, resp aplikacie vseobecne.
Ja by som to zavrela.

Hana Benediktová | Návody.Digital
hana.benediktova@slovensko.digital



pi 2. 8. 2019 o 11:14 Ernest Walzel <notifications@github.com> napísal(a):

**Comment by jsuchal** [comment]
Momentalne vieme dat odkaz na app rovno na titulku cize za mna uz irelevantne.
