### ISSUE TITLE
Nejde vymazat poduloha (v checkliste)

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#145]
dostanem err 500

**Comment by jsuchal** [comment]
@HanaBene toto sa ti podarilo vyriesit? Ono je to z pohladu produkcie tricky, nemali by sme to robit. Dovolene by malo byt len pridavat a "schovavat"

**Comment by HanaBene** [comment]
ano, vyriesene, zatvaram.
