### ISSUE TITLE
Zacat vybavovat odznovu ma nevrati uplne do nezacateho stavu

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#146]
Nezacaty stav: 
okrem buttonu (ten ma ist prec) nemam ani uvod checknuty
![targetprocess-screen-capture (13)](https://user-images.githubusercontent.com/45393631/55482695-60d71d80-5625-11e9-98fc-3eee93515d10.png)
Ked uz som vybavovala a kliknem zacat odznovu:
vratim sa do stavu ze uvod je done a zvysok je nevybaveny.
![targetprocess-screen-capture (14)](https://user-images.githubusercontent.com/45393631/55482697-62084a80-5625-11e9-8f88-6dc177e0a74c.png)

**Comment by jsuchal** [comment]
Fixnute v novom flowe.
