### ISSUE TITLE
Idea: counter k vybaveniu s deadline, napr ziadost o hlasovaci preukaz

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#147]
mohli by sme mat counter dni na zaslanie ziadosti
![counter](https://user-images.githubusercontent.com/45393631/55798315-ef88e600-5ace-11e9-9488-59f4da7f4a2c.PNG)

**Comment by jsuchal** [comment]
Toto nie je zly napad, avsak rozmyslam, ci na toto skor nie je lepsia notifikacia.

**Comment by HanaBene** [comment]
to bolo skor myslene, ked letmo klikas navody, tak aby si videl ten termin.
mozno do buducnosti, 
nie je to prioritne

**Comment by jsuchal** [comment]
@HanaBene mame k tomuto nejake tipy, ze na ktore navody by sa to hodilo?

**Comment by HanaBene** [comment]
appky. ziadost o hlasovaci preukaz, konecny uzivatel, danove priznania. notifikacie su super, to je taky aktivny sposob upozornenia, toto je take pasivne, ked sa nechces nikam prihlasovat, bojis sa spamu a pod. nice to have podla mna.

**Comment by jsuchal** [comment]
Spravil som zatial taketo:

![image](https://user-images.githubusercontent.com/26342/64911932-4c489680-d728-11e9-9439-52cd147a1b57.png)

Takto sa to pouziva

```
<deadline time='2019-11-01'>
 <i>nieco</i> sa tu deje.
</deadline>
```

Ale potrebujem zopar konkretnych pripadov, ze ci to bude stacit a potrebuje to ocividne trochu lasky grafika.

**Comment by crutch** [comment]
Tu som spisal ktore z navodov sa viazu na nejaky konkretny termin:

https://docs.google.com/spreadsheets/d/1m-GpPSQIlV4BQ9-X7QMIGtlWHjpDskf_tJUHlsY4Vsc/edit?usp=sharing

Mame dva typy a su to tieto tri:
1. jednorazove povinnosti/udalosti s pevne danym datumom
2. opakujuce sa (zatial to vyzera na rocnu frekvenciu)
3. danove priznania (opakujuce sa, ale navod sa vzdy vyrobi novy, pre dany rok)

**Comment by HanaBene** [comment]
Nasla som update zo stranky z horneho screenshotu, ide o notification banner. Ked uplynie doba odpoctu, vyzera takto:
![notification_banner](https://user-images.githubusercontent.com/45393631/197328780-ed25046a-6f7e-4602-9126-de2f416147b8.png)

Komponent v dizajn manuale> https://design-system.service.gov.uk/components/notification-banner/
Pouzitie na webe> https://www.gov.uk/government/consultations/learning-disability-and-autism-training-for-health-and-care-staff

**Comment by crutch** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/119724/197331688-482e425f-bef0-44bf-9c12-a2bb66aaee79.png">

<img width="759" alt="image" src="https://user-images.githubusercontent.com/119724/197331906-8648b7b4-c219-499e-8296-593e19c1847f.png">

Mozne zapisy:

Pre one time event:
```
<deadline time='2022-10-01'>
 <before>Založte si živnosť podľa <a href=/nieco> tohto návodu</a>.</before>
 <after>Ak ste to nestihli, založte si živnosť podľa <a href=/nieco> tohto návodu</a>.
</deadline>
```

Pre opakujucu sa udalost:
```
<deadline time='10-01'>
 <before>Založte si živnosť podľa <a href=/nieco> tohto návodu</a>.</before>
 <after>Ak ste to nestihli, založte si živnosť podľa <a href=/nieco> tohto návodu</a>.
</deadline>
```
Pri opakujucej sa udalosti sa pred datum doplni aktualny rok. Ak som za, tak zobrazujem <after> stav, ak som pred, tak <before> hlasku.

**Comment by HanaBene** [comment]
Este k tejto teme:
mame vo figme navrh od UXakov na counter na homepage 
![counter](https://user-images.githubusercontent.com/45393631/197332120-f9010ff9-53e9-46b4-bcd3-d5badccca777.png)

mozeme rozdiskutovat aj tuto verziu

figma tu https://www.figma.com/file/52FcEfWSNhnufVezLqDw9G/navody.digital?node-id=77%3A17

**Comment by crutch** [comment]
> Este k tejto teme: mame vo figme navrh od UXakov na counter na homepage ![counter](https://user-images.githubusercontent.com/45393631/197332120-f9010ff9-53e9-46b4-bcd3-d5badccca777.png)
> 
> mozeme rozdiskutovat aj tuto verziu
> 
> figma tu https://www.figma.com/file/52FcEfWSNhnufVezLqDw9G/navody.digital?node-id=77%3A17

@HanaBene ja si myslim, ze to je trochu ina feature a teda iny ticket.

**Comment by jsuchal** [comment]
Upozornenie podla gov uk je ok. Ale marginy su rozbite (hore dole iny) + mozno vacsi font dajme (ako gov uk to ma) - https://design-system.service.gov.uk/components/notification-banner/

**Comment by crutch** [comment]
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/119724/197353052-82ea11b0-5f49-4111-936b-2a2609d2f29d.png">

**Comment by celuchmarek** [comment]
@jsuchal túto issue tak môžeme zavrieť, či?

**Comment by HanaBene** [comment]
https://staging.navody.digital/zivotne-situacie/2-percenta-zamestnanec

Pouzila som zatial tu, funguje pekne. 

Este treba ucesat texty okolo a pouzit v inych situaciach, je ich dost najma v kategorii Financie a Podnikanie.

**Comment by HanaBene** [comment]
Snazim sa pouzit komponent v referendovom texte a nesedi mi ten wording. 
![deadline komponent](https://user-images.githubusercontent.com/45393631/204267096-e07be9d3-6da4-4299-a9c6-192efd191123.png)
Asi by bolo idealne, kebyze sa dotahuje len to cislo (n dní) a ja vložím text pred a za ako treba. 
Tu by som dala: Na zaslanie žiadosti ostáva ešte ....(dotiahnuté z komponentu).

**Comment by crutch** [comment]
Dobry napad, skusim sa na to pozriet cim skor tym skor.

**Comment by crutch** [comment]
@HanaBene pozri commit message vyssie ci Ti to takto pride pouzitelnejsie, je tam ukazka. V tom deadline komponente mas k dispozicii :remaining_days:, ktore sa nahradi za konkretne cislo + den/dni/dní.

**Comment by jsuchal** [comment]
@crutch dajme tam nejaky handlebars styl `{{remaining_days}}`
