### ISSUE TITLE
logo navody.digital

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#149]
pripravit logo navody digital, aby sedelo do temy slovensko.digital
![logosd](https://user-images.githubusercontent.com/45393631/55863503-eead8e00-5b7a-11e9-8d3c-61a1fd8382e7.PNG)

**Comment by HanaBene** [comment]
[logo_navody.zip](https://github.com/slovensko-digital/navody.digital/files/3112727/logo_navody.zip)

**Comment by jsuchal** [comment]
@HanaBene toto treba hodit do frontendu ako issue lebo v hlavicke to moze na mobile spravit celkom paseku.
