### ISSUE TITLE
Ako používateľ chcem zobraziť rozpracované návody

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#15]
- Ako prerekvizita sa musí užívateľ prihlásiť (pomocou magic link a email) ak už nie je prihlásený.
- Rozpracované úlohy by mal vidieť užívateľ ak príde na životnú situáciu a ak prihlásený tak by mal byť upozornený, že takéto niečo rozpracované má. Pozor wireframe:
![unnamed](https://user-images.githubusercontent.com/45393631/49230989-424fe400-f3f1-11e8-812c-8368d71839b9.png)
- Vpravo hore cez klik na meno/email a tam cez zoznam rozpracovaných úloh.

**Comment by jsuchal** [comment]
Idea je taka, ze ked som na navode a mam rozpracovanu taku ulohu tak sa mi to zobrazi hore v headeri.

Dalsia moznost je ked sa prihlasim (chcem zacat novu ZS) tak by ma to tiez malo upozornit ze pozor uz taku mam. Na uvod sme @filiplikavcan rozmyslali, ze dovolime mat rozpracovanu asi len jednu naraz (rovnakeho typu). => nemusime potom riesit identifikaciu ZS a tak. 

Zoznam rozpracovanych aj tak niekde potrebujeme.

**Comment by mirrec** [comment]
Uzivatel si musi manualne kliknut na to, aby sa dostal do rozpracovanej issue.
![screen shot 2019-02-14 at 16 22 05](https://user-images.githubusercontent.com/544111/52797015-3d581380-3075-11e9-9b83-32875160665c.png)

Vzdy sa vie dostat iba k poslednej.

**Comment by jsuchal** [comment]
Nakoniec sa vratime k rieseniu od @eronisko ze rovno sa ide na rozpracovanu. S tym, ze redirect pre neprihlaseneho by mal ist na statiku.

**Comment by jsuchal** [comment]
Toto odsuvame, kedze momentalne je podpora len pre 1 navod naraz. Naschval.

**Comment by michal-rohacek** [comment]
zatvaram, toto sa riesi v novej issue 

https://github.com/slovensko-digital/navody.digital/issues/388
