### ISSUE TITLE
Obrazky na frontpage su vo velkom rozliseni.

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#153]
Obrazky ako svadba su strasne velke a hrozne to spomaluje load prvej stranky. Mali by sme ich vyrazne zmensit. @filiplikavcan aka velkost je best practice?

**Comment by HanaBene** [comment]
zmensila som.

**Comment by eronisko** [comment]
Zase mame tento problem, najma s tymito obrazkami:
vyrub_drevin.jpg 1.8M
umrtie_blizke_osoby.jpg 410K
prepisauta.png 386K
2percenta.png 331K
kupa-bytu 161K
e-kasa 160K
mno.png 94K

Odporucam okrem zmensenia aj prehnat cez https://compressor.io/

**Comment by smith558** [comment]
@eronisko Mozem spravit
