### ISSUE TITLE
Pridat autocomplete attributy pre eu_vote_app

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/navody.digital#160]
Bolo by fajn autocomplete attributes na input fieldy, aby browser vedel doplnit meno/adresu/psc

meno: `name`
ulica a cislo: `street-address`
psc: `postal-code`
obec: `address-level2`

- https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
- https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

**Comment by jsuchal** [comment]
Inak na toto by si mohol skúsiť PR aj keby si to v živote nepustil. Pozeraj
view a tam apps folder.
