### ISSUE TITLE
Legal notice

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#164]
Niekde sme chceli prihodit do paticky tu "tieto informacie su len na informativne ucely". @HanaBene

**Comment by HanaBene** [comment]
taka bola rada od pravnikov, ale mame to v Podmienkach Pouzivania. 

Pripadne mozme pridat este do footeru, ale nejako sa mi to tam nepaci. 
@filiplikavcan co ty na to?

![targetprocess-screen-capture (16)](https://user-images.githubusercontent.com/45393631/56562479-b6aa4000-65a9-11e9-8eec-1e9341794de8.png)
