### ISSUE TITLE
Vizuálne odlíšiť notifikačný formulár v apke

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody.digital#174]
Staci obalit H3 a form divkom: <div style="border: 5px solid #fdef9e;padding: 30px;margin-bottom: 30px;margin-top: 90px;">

Plus poslednej govuk-form-group a buttonu v nej dat style="margin-bottom: 0";

![Screenshot 2019-04-24 at 11 49 02](https://user-images.githubusercontent.com/1244233/56650307-03177d80-6687-11e9-86a8-145a515cf006.png)

**Comment by jsuchal** [comment]
@filiplikavcan toto by asi chcelo normalne aj v komponentoch lebo na mobile to bude treba asi aby to malo ine medzery.

**Comment by filiplikavcan** [comment]
Na horny margin mozes pouzit govuk-!-margin-top-9 a bude to OK. Paddingy su ok aj na mobile.

**Comment by tajovic** [comment]
V inom threade riesime standardy na buttony. Tu su nejake dve alternativy:
![image](https://user-images.githubusercontent.com/11182227/70427446-02e0bc80-1a75-11ea-9c68-f73f9cc441fe.png)
[https://github.com/slovensko-digital/navody.digital/issues/306](306)

**Comment by HanaBene** [comment]
sede okno a ten modry button sa mi paci

**Comment by HanaBene** [comment]
toto je hotove
