### ISSUE TITLE
Inštruovať používateľa na poslednej obrazovke apky, čo má robiť ďalej

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody.digital#175]
Napr. jednoduchým textom takto: "Môžete zavrieť okno prehliadača alebo sa vrátiť na začiatok aplikácie. Nezabudnite si predtým nastaviť upozornenia na email nižšie."

![Screenshot 2019-04-24 at 11 53 45](https://user-images.githubusercontent.com/1244233/56650675-d0ba5000-6687-11e9-857f-1e7082de9909.png)

**Comment by filiplikavcan** [comment]
Vylepseny text, aby tam bolo explicitne uvedene, ze user je na konci:

"Hotovo! Teraz môžete zavrieť okno prehliadača alebo sa vrátiť na začiatok aplikácie. Nezabudnite si predtým nastaviť upozornenia na email nižšie."

**Comment by jsuchal** [comment]
Toto sa fixuje inak trosku, zatvaram
