### ISSUE TITLE
Radiobuttony Áno, Nie v apke dať pod seba

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody.digital#179]
![Screenshot 2019-04-24 at 12 08 07](https://user-images.githubusercontent.com/1244233/56651595-aff2fa00-6689-11e9-93e5-a564091fe6db.png)

**Comment by jsuchal** [comment]
Toto je presne podla dizajn manualu inak. https://design-system.service.gov.uk/components/radios/

**Comment by filiplikavcan** [comment]
Pisu tam, ze je moznost aj aj a mne v tom flowe to viac sedi pod sebou, aby to bolo konzistentne s inymi krokmi/obrazovkami.

**Comment by jsuchal** [comment]
@filiplikavcan rozumiem, na mobile to skoci pod seba, nerozumiem uplne preco maju toto pravidlo.

**Comment by eronisko** [comment]
Chceme toto este riesit?

**Comment by jsuchal** [comment]
Neviem na zaklade coho sa tu rozhodovat. Ja som sa rozhodoval podla toho, ze ked to je dostatocne kratke ze sa to zmesti vedla seba tak to dam vedal seba. @filiplikavcan ?
