### ISSUE TITLE
Ako používateľ chcem poslať spätnú väzbu

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#18]
- Podľa vzoru gov.uk (viď napr. https://www.gov.uk/browse/disabilities v lište dole “Is this page useful?” a “Is there anything wrong with this page?” skopírovať funkcionalitu).
- Malo by sa to zobrazovat na podstránkach FAQ/ŽS/podanie
- Logovanie responses pokojne niekam do google formu (v db by bolo kopec bordelu z tohto asi)
- Nice to have: Naviazat to na google analytics eventy (opät pozrieť čo loguje gov.uk)

**Comment by MiroBabic** [comment]
toto je podchytene v tomto PR, ku footeru je lista s textom "Je táto stránka užitočná?" moznostami Ano,Nie, Chyba, kde Ano priamo posle do formy submit, Nie ponukne formular s komentom a je na stranke chyba poskytne moznost dat email a vyziadat si dalsie info

https://github.com/slovensko-digital/navody.digital/pull/36

**Comment by HanaBene** [comment]
@MiroBabic  odpoved nie neponukne formular s komentom, je to nedorobene, alebo bug? 
Mozes sa na to prosim pozriet? Dakujem.

**Comment by jsuchal** [comment]
@HanaBene na toto stale chyba dorobeny komponent (ta cast ako ma gov.uk na zber komentov) cc @filiplikavcan
