### ISSUE TITLE
Flow medzi navodom a apkou

### ISSUE THREAD

**Issue by filiplikavcan** [slovensko-digital/navody.digital#183]
- user je strateny na konci apky (kde je navod? co dalej?) navrhujem https://github.com/slovensko-digital/navody.digital/issues/175
- odlisit nejak vizualne (mozno dat hore farebny badge), ze user je v apke, lebo jej prostredie vyzera ako navod, ale z nejakeho dovodu v nom zmizli kroky a kontext, pripadne by som uplne vypol navigaciu aj footer, aby z toho bol pocit ako z modalneho okna

Vypnuta navigacia, supersimple footer, badge:
![Screenshot 2019-04-24 at 12 29 01](https://user-images.githubusercontent.com/1244233/56652855-a919b680-668c-11e9-95e3-d28530c0bc8e.png)

**Comment by filiplikavcan** [comment]
![Screenshot 2019-04-24 at 12 34 08](https://user-images.githubusercontent.com/1244233/56653130-47a61780-668d-11e9-9286-cf1eb34d0721.png)

**Comment by jsuchal** [comment]
Trochu sa mi nepozdava graficky ten banner ale inak je to fajn, takto mozeme robit externe apps uplne hocikde lebo ziadny kontext tam neostava.

**Comment by filiplikavcan** [comment]
Apka by sa imho mala otvarat v rovnakom okne ako navod a v menu by bolo Zavriet, co by bol link back na url, z ktorej sa doslo. Na odkaze by bol onclick="return confirm('Naozaj?');" a bude ten flow uz uplne paradny.

**Comment by filiplikavcan** [comment]
Banner nemusi byt, ked to bude mat look&feel modalneho okna + nadpis sa moze zmenit na "Elektronická služba navody.digital"

**Comment by jsuchal** [comment]
Toto sa vyriesilo tak, ze pri podani je navrat na navod a pripadne to ide aj do mailu kde potom pokracujes dalej.
