### ISSUE TITLE
Flow aplikacii

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#185]
doriesit:
-vysledok aplikacie je, ze cakam = stav kroku by sa mal prepnut do waiting a mala by som sa vratit do navodu na ten krok
-vysledok aplikacie je done = stav kroku sa nastavi done a mala by som sa vratit do navodu

**Comment by HanaBene** [comment]
Workaround:
Do Co dalej? doplnit Vratit sa do navodu.

**Comment by jsuchal** [comment]
Ak niekto zacal v aplikacii tak sa nechce uplne asi "vratit" ale ked navrhnes wording dame to tam.

**Comment by HanaBene** [comment]
ked doklikas na koniec, tak tam je text co dalej. ci je to aj niekde skor?

**Comment by HanaBene** [comment]
zatvaram, rovnaka issue uz je https://github.com/slovensko-digital/navody.digital/issues/183
