### ISSUE TITLE
Frontend ako balicek

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#193]
Bude to chciet prejst na webpacker (asi rovno rails 6), ale bolo by dobre pouzivat frontend ako balicek, normalne verziovany. Otazkou ostava ako riesit cesty assets, ktore dnes mame fixnute takto https://github.com/slovensko-digital/navody.digital/blob/master/app/assets/stylesheets/navody-digital-fixes.scss.erb

@filiplikavcan pripadne @eronisko netusite ako sa to da vyriesit nejako elegantne?

**Comment by filiplikavcan** [comment]
Mame to ako npm package: https://www.npmjs.com/package/navody-digital-frontend

**Comment by jsuchal** [comment]
Tu cast chapem, skor ide o tie cesty k assets.

**Comment by eronisko** [comment]
Do railsov by malo ist pridat NPM baliky, pozriem to bleskovo

**Comment by jsuchal** [comment]
Ech, ano rails 6 to v pohode dava, riesim tie custom asset paths ktore su v
railsoch a v npm sa nane nebude dat asi odkazat :)

**Comment by filiplikavcan** [comment]
Ake assety myslis? Vo vseobecnosti by to malo byt naopak, ze asset manager (gulp, pipeline, Webpack, etc.) si zbundluje assety z roznych zdrojov (napr. npm balikov) a vypublikuje ich ako potrebuje. Nerozumiem teda, ze co je issue, resp. otazka.

**Comment by jsuchal** [comment]
Asset pipeline v rails generuje specialne nazvy suborov kvoli cachingu.
Toto je jedina issue co vidim.

**Comment by danielhusar** [comment]
V Intercome to mame takto:

`Intercom` repo je rails app kde nie je absolutne ziadny frontend, action view etc..
`Embercom` repo je ember aplikacia.

Ak sa mergne do mastra v `Embercome`, cd deployne fingerprinted assets na cdn, a posledny sha sa vlozi do dynamo db.

Rails app vzdy len pozrie do dynama ktore assets su posledne. (+ je tam nejaky caching)

Lokalne to funguje cez symlinky. (netusim ci by to fungovalo na windose)
Vyhoda je ze stale ked spravis zmenu na frontende, nemusis robit novy deploy celej rails app.
Nevyhoda asi trosku zlozitejsi setup lokalne.

**Comment by eronisko** [comment]
Hotovo v 45d80a6f510215ebe5b59ae407da43fc163e661c..c5247018fee6e5a11836caa8d5b8b56b0e06cfc1

Upgrade npm balika sa robi standardne cez `yarn upgrade navody-digital-frontend@<verzia>`, e.g. fc17ab1cca0a597a4c958410d8182e96728d7bfc

Lokalne moze mat developer aj iny ako publishnuty npm balik pomocou `yarn link` https://yarnpkg.com/lang/en/docs/cli/link/
