### ISSUE TITLE
Styling emailov

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#194]
Dnes posielame take suche emaily, chcelo by to trosku dizajnu. mozno nieco na styl gov.uk?

**Comment by danielhusar** [comment]
Ahoj, ak to este nikto nezacal tak by som to zobral :)

**Comment by danielhusar** [comment]
Co vravis napriklad na nieco taketo?
<img width="757" alt="Screen Shot 2019-05-24 at 23 39 50" src="https://user-images.githubusercontent.com/1857751/58365737-5430b200-7e7d-11e9-9b27-987b37d7e62b.png">

**Comment by jsuchal** [comment]
Gov uk vyzera nejako takto. 
![image](https://user-images.githubusercontent.com/26342/58365897-093d8b80-7ecb-11e9-9e0e-f2c5abaec4ae.png)

Hento co si poslal vyzera fajn, mozno by som tu paticku nejako skompresoval, resp. mozno ju tam vobec nedaval.

**Comment by danielhusar** [comment]
Oki :)

Tu ja par navrhov:


### 1
<img width="743" alt="Screen Shot 2019-05-25 at 10 37 59" src="https://user-images.githubusercontent.com/1857751/58372882-9556af80-7ed9-11e9-9466-80f6c15c39ca.png">

---
### 2
<img width="806" alt="Screen Shot 2019-05-25 at 10 44 04" src="https://user-images.githubusercontent.com/1857751/58372921-12822480-7eda-11e9-848f-31332f6d9b9a.png">

---
### 3

<img width="805" alt="Screen Shot 2019-05-25 at 10 43 43" src="https://user-images.githubusercontent.com/1857751/58372923-157d1500-7eda-11e9-8c96-a82b8091ceea.png">

**Comment by jsuchal** [comment]
Toto nevyzera zle, priklanam sa k 2. Este rozmyslam ci do toho headera nenapisat nejaky nadpis. @filiplikavcan ?

**Comment by filiplikavcan** [comment]
Nadpis v headri za mna moze byt.

**Comment by jsuchal** [comment]
Tak to failuje. https://circleci.com/gh/slovensko-digital/navody.digital/616

**Comment by jsuchal** [comment]
Fixol som.
