### ISSUE TITLE
aplikacia ZS narodenie dietata/materska: zaciatok a koniec materskej

### ISSUE THREAD

**Issue by janosvitok** [slovensko-digital/navody.digital#198]
Podla dobrych rad uja Mihala je vhodne urcit zaciatok a koniec materskej tak, aby nepripadol na zaciatok ani koniec mesiaca, lebo rodicovsky prispevok sa vyplaca za kazdy aj nacaty mesiac, zatial co materska sa vyplaca za kalendarny den.

Takze kto nastupi na matersku 1. 10. za oktober rodicovsky nedostane, a kto 2. 10. rodicovsky dostane. Podobne koniec. Ak som dobre pochopil, matka si moze zvolit zaciatok v rozmedzi 8-6 tyzdnov pred terminom, tak je dobre pri tom rozmyslat.

Cize pridat tam nieco ako TIP: ...

Dalsi TIP je: Ak nastupite na matersku neskor ako 8-6 tyzdnov pred terminom,  matersku neposuniete, ale vam ju patricne skratia.

**Comment by HanaBene** [comment]
Ahoj mas k tomuto nejaky dobry zdroj, aby som mohla sformulovat presne o co ide? Dakujem

**Comment by HanaBene** [comment]
Nasla som, ze narok na materske zanika uplynutim 34 tyzdnov od vzniku naroku, toto teda znamena, ze nie od zaciatku cerpania. Good point, zakomponujem to ako tip do navodu.

**Comment by jsuchal** [comment]
Ja by som do tychto tipov velmi nesiel, Mihal o tom vydava knizku skoro
kazdy rok, nechceme byt uplne pravna poradna a nemame na to ani kapacitu.

**Comment by HanaBene** [comment]
true, ale to info o 34 tyzdnoch tam podla mna patri. aj tam je, len to nie je take jasne. skusim to rpeformulovat.
