### ISSUE TITLE
HowTo datatype pre google

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#203]
https://developers.google.com/search/docs/data-types/how-to

**Comment by danielhusar** [comment]
Funguje to aj v Slovencine? Nejak sa neviem k tomu pregooglit ci ano :(

**Comment by jsuchal** [comment]
Vlastne skusam google a neviem ci to vobec funguje v EN. Googlim a nic take
mi to nevyhadzuje.

**Comment by crutch** [comment]
Zatvarame, duplicita s https://github.com/slovensko-digital/navody.digital/issues/324
