### ISSUE TITLE
Vsetky odkazy na slovensko.sk su presmerovane na www.slovensko.sk/saml/post/ac

### ISSUE THREAD

**Issue by wormyy** [slovensko-digital/navody.digital#207]
Ahojte, v prvom rade velka vdaka za tento projekt a za vsetko co robite.

Postupujem podla vasich navodov na zalozenie zivnosti a na aktivácia eID a elektronickej schránky ale vsetky odkazy z navody.digital (napriklad "Aktivovat schranku"), ktore by mali viest na relevantne miesto na Slovensko.sk su presmerovane na `https://www.slovensko.sk/saml/post/ac` kde sa zobrazi len blank page.

**Comment by HanaBene** [comment]
Ahoj,
diki za feedback, link bol zly, dala som tam pre tuto chvilu link na prihlasenie na portal. 
H.

**Comment by HanaBene** [comment]
opravene, toto nie je sluzba, neda sa pre to na to linknut, pridane do textu.
