### ISSUE TITLE
Custom title pre navod/krok

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#209]
Ako admin chcem mat moznost dat custom nazov (title) na navod alebo konkretny step. Tieto custom nazvy (ak su pritomne), by mali byt v title tagu, lebo tuto mierime na lepsie nazvy vo vyhladavacoch (SEO).

@HanaBene vies zmapovat co sa vyhladava?

**Comment by danielhusar** [comment]
Nazdar, kludne by som to implementoval ak sa nato este nikto nepodujal :)

Nazrel som trochu na strukturu, a aky je tvoj nazor vytvorit nejaky generic model, nieco ako `content` alebo tak ? (Kde by boli veci ako slug, title, content, meta (title, desc, keywords, share image) ...) pretoze momentalne sa to zbytocne duplikuje medzi 3 modely.

**Comment by HanaBene** [comment]
@jsuchal ako admin? nebol goal aby si pouzivatel zadal custom nazov napr Narodenie dietata (maly Jano)?
 
Ahoj @danielhusar, myslim, ze zrovna tuto ulohu mal Jano na muske uz, pocaj prosim kym sa vyjadri ;)

**Comment by jsuchal** [comment]
@danielhusar ahoj, tuto ulohu som interne uz pridelil prave, cize toto nerob. Mozno ma zmysel toto https://github.com/slovensko-digital/navody.digital/issues/203

**Comment by danielhusar** [comment]
Oki :) Inac co hovoris na tu druhu cast mojej otazky? 

> Nazrel som trochu na strukturu, a aky je tvoj nazor vytvorit nejaky generic model, nieco ako content alebo tak ? (Kde by boli veci ako slug, title, content, meta (title, desc, keywords, share image) ...) pretoze momentalne sa to zbytocne duplikuje medzi 3 modely.

**Comment by jsuchal** [comment]
@danielhusar hovorim, ze premature optimization. :)

**Comment by danielhusar** [comment]
fair :)

**Comment by smith558** [comment]
Implementujem
