### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by danielhusar** [slovensko-digital/navody.digital#212]
Nazdar, aky je nazor aby content sa dal pisat v markdowne? 

Vyzera to, ze momentalne je to plain html, cize markdown by mal byt spatne kompatibilny so vsetkymi clankami, a je ovela viac user friendly na pisanie clankov :)

**Comment by jsuchal** [comment]
Skor je otazka, ze co tym ziskame. lebo plain html vies pouzit aj staticky (tak niektore navody vznikaju) a potom to len copy&paste a mas. Toto by sme stratili.

**Comment by danielhusar** [comment]
No je to iba napad :) 

Zamna ziskas rychlejsie pisanie clankov, ale chapem ked v tom nevidis velmi vyhodu.
BTW html je subset markdownu, takze ak nieco napises staticky a potom pastnes to adminu, stale by to malo fungovat.

**Comment by jsuchal** [comment]
Zatial to zavrieme, kedze nam to asi vela nepridava.
