### ISSUE TITLE
Testy z forknutych repositarov

### ISSUE THREAD

**Issue by danielhusar** [slovensko-digital/navody.digital#214]
Defaultne circle nebuilduje pull requesty z forkov:

https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

> **Build Pull Requests From Forked Repositories**
Many open source projects accept PRs from forked repositories. Building these PRs is an effective way to catch bugs before manually reviewing changes.

> By default, CircleCI does not build PRs from forked repositories. To change this setting, go to the Advanced Settings of your project and set the Build forked pull requests option to On.

**Comment by jsuchal** [comment]
Toto asi nebude uplne klik-klik, lebo nam CI do rovno aj deployne, @eronisko ty si to nastavoval tu https://github.com/slovensko-digital/navody.digital/blob/master/.circleci/config.yml netusis ako to spravit na PR tak, aby to zbehlo len testy bez deploy?

**Comment by eronisko** [comment]
Zda sa ze filtrovanie podla PR v CircleCi 2.0 zatial chyba: https://discuss.circleci.com/t/how-to-set-the-owner-filter-in-circle-ci-2-0/20443

Dalo by sa filtrovat podla [`$CIRCLE_PR_NUMBER`](https://discuss.circleci.com/t/how-to-set-the-owner-filter-in-circle-ci-2-0/20443/6) (v PR je to nastavene, v origine nie), ale zatial neviem kam by to slo.

A quick-fix by bol nasadzovat manualne, teda vypnut deploy v CircleCi a iba zapnut to co vravi @danielhusar hore.

**Comment by danielhusar** [comment]
Tu je tiez nejaky [navod](https://discuss.circleci.com/t/create-separate-steps-jobs-for-pr-forks-versus-branches/13419) ja si ale myslim ze by to malo fungovat bez ziadnej zmeny v configu.

Vidim ze deployues len master, a ten je len jeden v tomto repo. Akonahle to forknem uz je to iny master a ja by som svoj fork musel nakonfigurovat na circle ak by som chcel svoje push buildovat bez toho aby som spravil PR. 

Ak spravim z neho PR (hoc som pushoval rovno do mastra) tvoj master stale nema ziadne zmeny a mal by spravit deploy az ked mergnes moje PR.

**Comment by eronisko** [comment]
Malo by to byt. `CC_TEST_REPORTER_ID` sa mi odtial nepodarilo vyhodit (lebo do fork buildov mozes bud pustit obe, ENV aj secrets, alebo ani jedno), ale nepovazujem to za secret (kedze to doteraz bolo v kode).
