### ISSUE TITLE
Odoberanie sprav v strede navodu

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#219]
V niektorych navodoch by sa nam hodil komponent (pre prihlasenych aj anonymnych), ze by sa clovek mohol prihlasit k odberu nejakej notifikacie. Treba identifikovat pre ktore navody to ma zmysel (napriklad volby, etc) a dorobit podporu pre subscribe notifikacie (komponent a logika je hotova v aplikacii volieb). Treba to len vediet cez nejake xml (?) znacky dostat do navodu samotneho.

**Comment by marosj** [comment]
Ked som si uz zapol notifikaciu a zobrazim si navod znova, co sa ma zobrazit? Nic, alebo kratke info (Notifikacie XY mate zapnute), alebo komponent s hodnotami, ktore som zadal (a teraz ich mozem zmenit)?

**Comment by HanaBene** [comment]
toto uz je riesene? podla mna komponent s hodnotami. 

co sa tyka mailing listov kam sa to pridava, to sme doriesili @jsuchal? volby maju vlastny list, ostatne ZS by mali mat general, nebudeme schopni udrziavat viac mailing listov. uz teraz mame tusim 4, treba to zjednotit do max dvoch.

**Comment by jsuchal** [comment]
Za mna su to dve rozdielne veci. Jedna vec je komponent v navode (tam by som mal vidiet, ze to mam zapnute + moznost vypnut) a potom nejaky prehlad vsetkych notifikacii co mam zapnutych v profile (to odsunme nateraz)

**Comment by HanaBene** [comment]
Ako je na tom toto? Doriesime na Hackday, ci mame to nejako uzavrete? @jsuchal

**Comment by smith558** [comment]
To be implemented

**Comment by jsuchal** [comment]
Toto je hotovo, resp. su na to separe issues na ktorych sa robi.
