### ISSUE TITLE
Objektom pridať keywords 

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#22]
Mal by som vedieť indexovateľným objektom (ŽS/procesný krok/otázka) pridať keywords, podľa ktorých sa bude dať hľadať.
- typicky synonymá (zmena trvalého bydliska, zmena bydliska, sťahujem sa..)

**Comment by eronisko** [comment]
Spravene v c82f266edc5c4618a428c6e356f8231507a5fc24

**Comment by jsuchal** [comment]
@HanaBene Toto ma este softovu cast, k ZS by sme mali tieto klucove slova aj pridat, aby sa to dalo vyhladavat.
