### ISSUE TITLE
Všetky odkazy 'von' by sa mali otvárať v novom okne

### ISSUE THREAD

**Issue by mirrec** [slovensko-digital/navody.digital#220]
Napriek tomu, že odkazy majú ikonku, ktorá informuje, že sa odkaz otvorí v novom okne (apoň teda predpokladám, že to tak chce byť), sa niektoré odkazy neotvárajú v novom tabe.

Otázka je, či by sa to nemalo / nedalo nejak automatizovať.

https://navody.digital/zivotne-situacie/volby-do-eu-parlamentu

![Screen Shot 2019-06-08 at 10 58 13](https://user-images.githubusercontent.com/544111/59144896-b096e400-89dc-11e9-9742-7703fa462f0e.png)

https://navody.digital/zivotne-situacie/zalozenie-zivnosti/krok/zalozte-si-bankovy-ucet

![Screen Shot 2019-06-08 at 10 59 01](https://user-images.githubusercontent.com/544111/59144898-b4c30180-89dc-11e9-8017-50a5db27de35.png)

**Comment by HanaBene** [comment]
mali by sa otvarat v novom okne, vieme to automatizovat @jsuchal ? 
kazdopadne tie hore spomenute som opravila

**Comment by danielhusar** [comment]
Toto by som inac velmi neodporucal.
https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba

**Comment by eronisko** [comment]
Ta ikonka je matuca, ale znamena, ze ide o externy odkaz, nie, ze sa ma otvorit v novom okne.

Za mna by som dal ikonku prec a radsej to tam vypisal slovom. Maju to tak aj v Gov UK: https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/
cc @filiplikavcan 

Co sa tyka otvrania v novom okne, nechal by som toto rozhodnutie na pouzivatela a radsej sa spraval konzistentne.

**Comment by eronisko** [comment]
Rozhodli sme sa toto neimplementovat. Mozno existuju odkazy, ktore by sa mali otvarat v novom okne, ale viaceri sme sa zhodli ze ako default to nie je vhodne.

Suhlasim, ze s ikonkou je to matuce, ale to je problem ikonky. (Nestastne) oznacuje externy link, nie otvorenie v novom okne. Vid napr https://ux.stackexchange.com/a/107824/69452
