### ISSUE TITLE
Pretekajúci odkaz na 'Zaregistrujte sa na DPH'

### ISSUE THREAD

**Issue by mirrec** [slovensko-digital/navody.digital#222]
Na https://navody.digital/zivotne-situacie/zalozenie-zivnosti/krok/zaregistrojte-sa-na-dph

je zle vložený odkaz. Spôsobuje to, že sa nedá nikde inde klikať.
![Screen Shot 2019-06-08 at 11 22 31](https://user-images.githubusercontent.com/544111/59145105-c2c65180-89df-11e9-9471-94f106442508.png)

**Comment by HanaBene** [comment]
fixed
