### ISSUE TITLE
Písať potrebné kroky / prílohy atď jednodným štandardom 'Ak, tak'

### ISSUE THREAD

**Issue by mirrec** [slovensko-digital/navody.digital#223]
aktuálna verzia (toto, ak)
- **doklad o vašej odbornej spôsobilosti** alebo spôsobilosti zodpovedného zástupcu (v takom prípade aj jeho súhlas s ustanovením do funkcie), **ak budete** ohlasovať viazanú ak budete ohlasovať viazanú alebo remeselnú živnosť

žiadaná verzia (ak, tak toto)
- **ak budete** ohlasovať viazanú ak budete ohlasovať viazanú alebo remeselnú živnosť **tak doklad** o vašej odbornej spôsobilosti alebo spôsobilosti zodpovedného zástupcu (v takom prípade aj jeho súhlas s ustanovením do funkcie)

Problém zápisu (toto, ak) je, že ma zahltí informáciami, ktoré sa ma vôbec nemusia týkať. Celý proces môžem opustiť a začať si dohľadávať informácie typu "čo je odborná spôsobilosť". Ak si vetu nedočítam, tak nezistím, že sa ma daná vec netýka.

Výhodou zápisu (ak, tak toto) je to, že môžem veľmi rýchlo vyhodnodiť, že sa ma niečo netýka a nemusím čítať ďalej. Celé to prejdem rýchlejšie, a mám pocit, že to je jednoduhšie. Presne takto je písaný tretí bod.

https://navody.digital/zivotne-situacie/zalozenie-zivnosti/krok/ohlaste-svoju-zivnost

![Screen Shot 2019-06-08 at 11 47 52](https://user-images.githubusercontent.com/544111/59145382-6d8c3f00-89e3-11e9-9dd5-25600a82000e.png)

**Comment by HanaBene** [comment]
upravila som a pridavam to do guidelinu na pisanie navodu.
