### ISSUE TITLE
'Sa mi nedá vycentrovať' na prihlasovacej obrazovke

### ISSUE THREAD

**Issue by mirrec** [slovensko-digital/navody.digital#224]
Neviem či prihlasovacia obrazovka https://navody.digital/session/new chce vyzerať takto.

![Screen Shot 2019-06-08 at 10 24 58](https://user-images.githubusercontent.com/544111/59145329-8cd69c80-89e2-11e9-9371-88dfd600e23b.png)

**Comment by smith558** [comment]
Seems to be resolved now

**Comment by HanaBene** [comment]
bol tam nejaky problem, vsetky headiny boli centered, uz je to fixnute.
