### ISSUE TITLE
Pri user registrácii s emailom chýba email validation

### ISSUE THREAD

**Issue by smith558** [slovensko-digital/navody.digital#230]
![image](https://user-images.githubusercontent.com/44023416/59150687-87e80c00-8a27-11e9-8b30-09b24476c267.png)

**Comment by eronisko** [comment]
Ako som pisal v PR: chyba este back-end validacia, ale kedze aj tak overujeme usera e-mailom je toto podla mna good enough.

**Comment by jsuchal** [comment]
@eronisko - validaciu serverside chceme urcite, lebo ked posielame maila tak to failuje.

@HanaBene - tiez dajme do hackday milestone.

**Comment by eronisko** [comment]
Pointa bola, že e-mail je defaultne zvalidovaný client-side. Ak by si aj niekto client-side validáciu naschvál vypol, je mu to nanič, email mu nepríde.
