### ISSUE TITLE
Deaktivovat/upravit appku EU volby

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#233]
Tak, aby bolo jasne, ze uz je to neaktualne, aj ked sa tam prekliknes z odkazu.

**Comment by jsuchal** [comment]
@HanaBene Asi ma zmysel tam dat subscribe na dalsie volby, @danielhusar pozries na to?

**Comment by danielhusar** [comment]
Ahoj, jasne mozem na to pozriet.
Kam by ten subscribe mal ist?

Pouzit tento form?

<img width="478" alt="Screen Shot 2019-06-26 at 16 50 18" src="https://user-images.githubusercontent.com/1857751/60222520-8180cf00-9832-11e9-8545-feb168556d18.png">

**Comment by jsuchal** [comment]
Je tam komponent hotovy co sa pouziva v app na subscriptions. Cize treba vybrat nejake relevantne subscriptions a dat ich tam
