### ISSUE TITLE
idea: FAQ na homepage nezobrazovat na novej stranke

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#235]
nie je velmi dovod mat dvojvetove otazky na vlastnej stranke, 
mohli by sme tam pouzit komponent Accordion a iba rozrolovat odpoved priamo na homepage. 
![cko](https://user-images.githubusercontent.com/45393631/60575840-8f77a800-9d7c-11e9-961f-6791a1c6c9d5.PNG)
![cko2](https://user-images.githubusercontent.com/45393631/60575842-90103e80-9d7c-11e9-90b4-b4cbee61f6ec.PNG)

**Comment by HanaBene** [comment]
@filiplikavcan co myslis?

**Comment by filiplikavcan** [comment]
Paci sa mi tato myslienka.

**Comment by danielhusar** [comment]
Ahoj, mozem na to pozriet ak to este nikto nezobral :)

**Comment by HanaBene** [comment]
Parada!

**Comment by eronisko** [comment]
Fixnute v #240
