### ISSUE TITLE
Ako pouzivatel chcem zadat svoju adresu zadanim PSC

### ISSUE THREAD

**Issue by eronisko** [slovensko-digital/navody.digital#24]
Priklad: https://design-system.service.gov.uk/patterns/addresses/

Databaza PSC napriklad tu: https://www.posta.sk/sluzby/postove-smerovacie-cisla (ale je mozne ze niekde uz existuje aj lepsie spracovana)

**Comment by jsuchal** [comment]
Toto u nás nefunguje lebo psc je u nás tisíce adries. Ale máme register
adries a alebo Google maps.

**Comment by eronisko** [comment]
OK, zatvaram
