### ISSUE TITLE
Navod v stave draft - neda sa zobrazit uvod, ale vsetko ostatne ano

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#241]
Ked mame navod v stave draft, neda sa zobrazit uvodna stranka, ale dalsie kroky ano. 
Neviem ci to niecomu vadi, ale nemalo byt to byt konzistentne? 

Any thoughts? @eronisko

**Comment by eronisko** [comment]
A chceme aby sa navody v stave draft zobrazovali, alebo nie?

**Comment by HanaBene** [comment]
Podla mna nech sa nezobrazuje nic.
