### ISSUE TITLE
Zintegrovat sendinblue mailing list po prihlaseni sa na odber cez app

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#245]
Ked sa user prihlasi na odber noviniek cez appku (nie cez ten footer), tak to je len u nas interne. bolo by dobre to zintegrovat zo sendinblue, nech to tam prihodi do spravneho listu (bacha na confirmation email ak to neni prihlaseny user).

https://developers.sendinblue.com/docs/

**Comment by martyciz** [comment]
#250

**Comment by jsuchal** [comment]
Toto je hotovo, zatvorime ked @HanaBene importne do sendinblue emaily.

**Comment by HanaBene** [comment]
kontakty su naimportovane v sendinblue v listoch volby, newsletter a euvolby
