### ISSUE TITLE
Server side validacia na email + presence pri prihlaseni cez email

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#247]
V subscription a v prihlasovani treba overit ci validujeme email a pritomnost. Pri prihlasovani mam pocit, ze to zoberie aj prazdny email.

**Comment by eronisko** [comment]
#230 som zatvoril priskoro, ale podla mna by tu stacila aj ta client-side validacia (`required: true`)

**Comment by tomas-radic** [comment]
Ahojte, redirect na sessions#new sa mi nepodarilo vyriesit, ale urobil som nasledovne:

Formular (frontend) validuje presence a email format. HTML5 email format ale pusti aj input ako "tomas@radic" (akoby bodka domena tam nemusela byt) - presne tak isto sa sprava aj tento regex: URI::MailTo::EMAIL_REGEXP

Preto som teda nakoniec tento regex dal do naseho EmailValidatora - aby korespondoval s frontendovou validaciou, ktoru tam teraz uz mame. Cize frontend formular mame upraveny, ze pusti iba inputy zodpovedajuce URI::MailTo::EMAIL_REGEXP a na backende, ak by predsalen prisiel iny vstup (co sa normalne nestane) vyhodime exception.

Inak neviem ako z tej MagicLink strategie by sme sa redirectovali na sessions#new - pripadne mozno @alhafoudh nieco poradi?

@jsuchal @eronisko
