### ISSUE TITLE
Zobrazit datum poslednej upravy

### ISSUE THREAD

**Issue by eronisko** [slovensko-digital/navody.digital#256]
Bolo by super ukazovat datum poslednej upravy navodu, aby clovek vedel ci postupuje podla aktualnych instrukcii.

**Comment by lukas-manduch** [comment]
Ahoj @jsuchal, poprosim assignut na mna. Vdaka

**Comment by jsuchal** [comment]
@lukas-manduch toto asi nebude take jednoduche, lebo by to znamenalo ze hocijaky preklep opraveny by zmenil datum. Ja by som tam vyslovene pridal nejaky `last_checked_on`, ktory budeme rucne updatovat v adminovi. Biznisovo toto totiz znamena, ze mozno bude treba cely navod prejst s pravnikmi ci je aktualny, overit linky... to sa urcite nedeje pri kazdom update. 

Cize za mna: 
- pridajme tam field na toto, ak je nil nezobrazujeme.
- v adminovi dajme moznost editovat to. v klude html5 calendarik
- mozno by som zvazil aj nejaky warning hore ze ked to je starsie ako rok, tak to hore bude kricat.
- malo by sa to zobrazovat asi na kazdom step, ale field bude na urovni celeho journey.

Dava zmysel?

@PetraPlesnikova prejst vsetky navody a dat tam "stemplel" ze k tomuto datumu je to ok. Zatial to mozeme zbierat do excelu.
