### ISSUE TITLE
update aplikacie volby.digital pre potreby parlamentnych volieb

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#262]
TODO
- [x] https://github.com/slovensko-digital/navody.digital/issues/262#issuecomment-552360501
- [x] FB meta obrazok
- [x] volby.digital redirect + obrazok
- [ ] notification step pred posledny krok (nice to have)

tak ako pre EU volby, chceme mat na portali aplikaciu pre ziadost o hlasovaci preukaz. 
oproti poslednej verzii to tentokrat bude dostupne priamo z homepage, nebude samostanty navod - informacie budu obsiahnute v aplikacii. 

uvodny screen:
informacie o volbach, zaklad - zatial toto, postupne upravime, doplnime.
Najbližšie riadne parlamentné voľby sa na Slovensku budú konať začiatkom roka 2020 (pravdepodobne 29. februára 2020). Občania Slovenskej republiky volia 150 poslancov do Národnej rady SR na volebné obdobie 4 roky. Právo voliť má každý občan SR, ktorý najneskôr v deň volieb dovŕši vek 18 rokov. 
Volič môže voliť na území Slovenska vo volebnom okrsku podľa miesta trvalého pobytu alebo v ktoromkoľvek volebnom okrsku na základe hlasovacieho preukazu. Mimo územia Slovenskej republiky je možné voliť poštou.

Pomocou tejto služby si môžete vytvoriť žiadosť o hlasovací preukaz. 

counter s odpocitavanim dni do deadline na podanie ziadosti a deadline na volebny den

button zacat 

![parlamentne volby](https://user-images.githubusercontent.com/45393631/64412129-06883000-d08f-11e9-8424-dc90e3bdc5b4.jpg)

**Comment by jsuchal** [comment]
@danielhusar tuto je issue. ja by som zobral appku na eu volby copy&paste a zacal upravovat podla flowu.

**Comment by danielhusar** [comment]
Super :) Tento tyzden nato pozriem

**Comment by danielhusar** [comment]
Flow uz mam *skoro* hotovy.
Chcelo by to mozno nejaky google doc s textami :)

**Comment by HanaBene** [comment]
![parlamentne volby](https://user-images.githubusercontent.com/45393631/64909677-b56fe000-d70f-11e9-9060-33753eb5f2fe.png)
@danielhusar doplnila som este jednu otazku do flowu - ked volis v zahranici, posielas ziadost na obec/min vnutra podla toho ci mas trvaly pobyt na slovensku alebo nie. 

texty coming soon, davam to dokopy.

**Comment by danielhusar** [comment]
Pridane :)

**Comment by jsuchal** [comment]
@danielhusar niekedy su pod foldom errory - toto by stalo za to prihodit do APP. https://design-system.service.gov.uk/components/error-summary/ a do buildera.

nice-to-have feature
