### ISSUE TITLE
pridat text k blank navodu na volby

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#266]
pred subscribe pridat prosim zhrnutie:

Najbližšie riadne parlamentné voľby sa na Slovensku budú konať začiatkom roka 2020 (pravdepodobne 29. februára 2020). Občania Slovenskej republiky volia 150 poslancov do Národnej rady SR na volebné obdobie 4 roky. Právo voliť má každý občan SR, ktorý najneskôr v deň volieb dovŕši vek 18 rokov. 

Volič môže voliť **na území** Slovenska vo volebnom okrsku podľa miesta trvalého pobytu alebo v ktoromkoľvek volebnom okrsku na základe hlasovacieho preukazu. **Mimo územia** Slovenskej republiky je možné voliť poštou.

Podrobný návod kde a ako hlasovať, ako získať hlasovací preukaz a ako požiadať o voľbu zo zahraničia Vám prinesieme po oficiálnom vyhlásení dňa konania parlamentných volieb.

podtym subscribe na mailoch,
overit, ze dobre ukladame adresy.

**Comment by jsuchal** [comment]
@HanaBene na stagingu by sa mali ku *vsetkym* blank navodom uz zobrazovat aj description. cize treba popozerat ci tam nie su nejake hluposti (napr. description slovo) - taktiez plati ze nie je povinne to pre blank vyplnit

**Comment by HanaBene** [comment]
na stagingu nemame blank navody - iba testovaci. 
ked to bude na produkcii tak zrusim tie hluposti a doplnim relevantne, napr k volbam.
