### ISSUE TITLE
search "prepis vozidla" na navodoch listuje najprv blank navody az potom realny vysledok

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#268]

**Comment by mortenko** [comment]
na locale to listuje dobre na produkcii to nefunguje

**Comment by martyciz** [comment]
mozne riesenie je ignorovat dlzku dokumentu pri rankovani searchu. Vieme si nejako overit, ci to nepokazi cely search? :)

**Comment by jsuchal** [comment]
@HanaBene uvazujem ze ci nejako neoznacit tie nehotove navody nejako. nejaky "stitok" - "Plánovaný návod" alebo niečo také?

**Comment by HanaBene** [comment]
to by bolo super. ako je phase banner https://frontend.navody.digital/custom-components/phase-banner, ale Plánovaný návod? 
👏

**Comment by jsuchal** [comment]
Taketo https://frontend.navody.digital/components/tag ale asi menej vyrazne.
