### ISSUE TITLE
Custom názov návodu

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#27]
Viem si návod nejako nazvať (ak to dáva zmysel a môžu byť súbežné. Napr viacero rovnakých žiadostí) - väčšinou by sa tak malo stať automaticky z metadát, čo sa zozbierajú.
_Na toto bude treba API/definiciu, ze ako to nazvat napr. pri narodeni dietata ma zmysel tam dat meno dietata. Pri aute asi znacku/typ - farbu alebo nieco take._

**Comment by jsuchal** [comment]
Toto by sa malo tykat nielen nazvu navodu, ale mat moznost dat custom nazov (title) aj na konkretny step. Tieto custom nazvy (ak su pritomne), by mali byt v title lebo tuto mierime na lepsie nazvy vo vyhladavacoch (SEO).

@HanaBene vies zmapovat co sa vyhladava?

**Comment by eronisko** [comment]
Zaklad implementacie v #216

**Comment by jsuchal** [comment]
Zatial nepodporujeme subezne navody cize zatvaram.

**Comment by HanaBene** [comment]
Toto niekto rozrobil, ide o to, ze v admine je mozne pridat custom nazov,
ktory sa ti potom zobrazuje v nazve tabu.
To je nieco ine, nez je ucel tejto funcionality.

Hana Benediktová | Návody.Digital
hana.benediktova@slovensko.digital



so 19. 9. 2020 o 11:09 Jano Suchal <notifications@github.com> napísal(a):

**Comment by jsuchal** [comment]
@HanaBene ano ta cast je hotova.
