### ISSUE TITLE
BlankJourneySubscription nepriraduje journey ked je volany cez raw_with_custom_components

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#280]
Tuto https://github.com/slovensko-digital/navody.digital/blob/master/app/helpers/custom_components_helper.rb#L11 by mal ist aj parameter `journey:`, aby sa to pre BlankJourneyNotification typ nastavilo.

Taktiez pre model SubscriptionNotification by sme mali vynutit validaciu na presence ked je to tohto typu (testy by mali zacat failovat, ked to pridame)

Treba upravit aj `raw_with_custom_components` aby mal optional `journey:` parameter.

**Comment by mortenko** [comment]
https://github.com/slovensko-digital/navody.digital/pull/283
