### ISSUE TITLE
blank navody v searchi nelistuju vysledky z keywords

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#281]
pozri konenceho uzivatela vyhod, 
zs sa vola prihlasenie konecneho uzivatela vyhod, 
teda keyword konecny, uzivatel a pod, nenajde vysledok

**Comment by MiroBabic** [comment]
skusil by som set_limit(real) nastavit na nizsiu hodnotu

**Comment by jsuchal** [comment]
@MiroBabic toto suvisi ako? Podla mna tam je bug v db lebo lokalne to ide.

**Comment by MiroBabic** [comment]
ako lokalne? ja som pozeral ten gem, ten si robi vektory z textu a nasledne podla similarity urcuje ci si sa trafil alebo nie...neviem ako mate nastevenu default hodnotu, ale je mozne ze vas produkcny postgres ma inu hodnotu

**Comment by jsuchal** [comment]
Na localhoste to funguje. set_limit sa tyka trigram searchu, to vobec pokial viem nepouzivame.

**Comment by MiroBabic** [comment]
ale pouzivate, prave preto to spominam, pozeral som aky gem na to mate a vase migracie
https://github.com/slovensko-digital/navody.digital/blob/master/db/migrate/20190301173059_create_pg_search_documents.rb

**Comment by jsuchal** [comment]
Opakujem, trigram sa nepouziva. Nevidim to nikde v definicii https://github.com/slovensko-digital/navody.digital/blob/master/app/models/pg_search/document.rb#L17-L27 a query neobsahuje nic trigramove.

```
PgSearch::Document Exists? (35.6ms)  SELECT 1 AS one FROM "pg_search_documents" INNER JOIN (SELECT "pg_search_documents"."id" AS pg_search_id, (ts_rank((setweight(to_tsvector('simple', coalesce("pg_search_documents"."keywords"::text, '')), 'A') || setweight(to_tsvector('simple', coalesce("pg_search_documents"."title"::text, '')), 'A') || setweight(to_tsvector('simple', coalesce("pg_search_documents"."content"::text, '')), 'D')), (to_tsquery('simple', ''' ' || 'hovno' || ' ''')), 1)) AS rank FROM "pg_search_documents" WHERE ((setweight(to_tsvector('simple', coalesce("pg_search_documents"."keywords"::text, '')), 'A') || setweight(to_tsvector('simple', coalesce("pg_search_documents"."title"::text, '')), 'A') || setweight(to_tsvector('simple', coalesce("pg_search_documents"."content"::text, '')), 'D')) @@ (to_tsquery('simple', ''' ' || 'hovno' || ' ''')))) AS pg_search_ce9b9dd18c5c0023f2116f ON "pg_search_documents"."id" = pg_search_ce9b9dd18c5c0023f2116f.pg_search_id WHERE "pg_search_documents"."searchable_type" IN ($1, $2, $3) LIMIT $4 OFFSET $5
```

**Comment by MiroBabic** [comment]
ok moja chyba :) za skusku ale nic nedas ak si docasne upravis set_limit a otestujes

**Comment by jsuchal** [comment]
@HanaBene ehm. v adminovi bolo **koneNcny**.

**Comment by HanaBene** [comment]
mea culpa, zatvaram. druhy task na search ostava.
