### ISSUE TITLE
destroy task nefunguje

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#282]
dostanem Nieco sa pokazilo page

**Comment by jsuchal** [comment]
Poznamka: Toto je pravdepodobne sposobene tym, ze niekto ten krok/task oznacil ako urobeny (v todo liste). Tieto pripady su problematicke lebo len tak zmazat to nemozeme (asi)

**Comment by HanaBene** [comment]
ked mame situaciu ze sa zmeni legislativa, proces, cokolvek, proste uz je ten task nerelevantny? ma tam zostat?
