### ISSUE TITLE
Facelift homepage

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#286]
S pribudajucimi navodmi potrebujeme kategorizovat navody a zobrazovat na uvodnej stranke len skupiny/kategorie.
Navrh vizualu: 
![Home](https://user-images.githubusercontent.com/45393631/67191046-4150e800-f3f1-11e9-9a96-e5f562e18d3a.png)

Vnutri kategorie:
![Kategoria](https://user-images.githubusercontent.com/45393631/67191059-4a41b980-f3f1-11e9-9bfa-268f4f511465.png)

Treba:
- [ ] Zaviest kategorie (asi po vzore slovensko.sk) - definovat kazdemu navodu jeho prislusnost
- [ ] pripravit pouzitie komponentu Aktualna tema (na vizuali Horuca tema)- uz sa riesilo vo frontendovom repe, treba k tomu aj graficke spracovanie
- [ ] Zvazit uvodnu informacnu vetu na homepage, aby clovek pri prvej navsteve videl o co ide. Pod logo. Nieco ako: Jednoduché návody, na vybavenie úradných záležitostí./Jednoduché návody na slovenské úrady.
- [ ] Logo Navody
- [ ] bannery ZS 
- [ ] ...

discuss..!

**Comment by HanaBene** [comment]
@jsuchal pls hod svoj nazor ked budes mat cas, 
nech to mame spisane, co chceme urobit.
Diki.

**Comment by HanaBene** [comment]
Navrh riesi z komunity Ondrej Culko.

**Comment by tajovic** [comment]
Wow. Velmi pekne a posobi to na mna prehladne.

**Comment by jsuchal** [comment]
Tie kategorie sa mi pacia, ale tento detail mi pride, ze ten text je prilis dlhy.

![image](https://user-images.githubusercontent.com/26342/70415820-d0779500-1a5d-11ea-8dec-802ea6e76b8f.png)

Vieme skusit vyrobit tie kategorie s aktualnymi datami, ze kolko by sme tam toho mali?

**Comment by HanaBene** [comment]
navrh vo figme: https://www.figma.com/file/52FcEfWSNhnufVezLqDw9G/navody.digital?node-id=77%3A17

**Comment by TomasMakan** [comment]
> navrh vo figme: https://www.figma.com/file/52FcEfWSNhnufVezLqDw9G/navody.digital?node-id=77%3A17

Do figmy sme doplnili niekoľko verzií home page ( prevažne sme využili textové komponenty) nasledovne:
Home page -> submenu (detail kategórie + členenie do oblastí) -> submenu na úrovni konkrétnych návodov

**Comment by HanaBene** [comment]
kategorie nastrel tu https://docs.google.com/spreadsheets/d/1I4pX4YEtXYV4s8YZEWRbHcaYD_mxhYMQoK9MQN_O_cE/edit#gid=1109359508

cc @jsuchal

**Comment by TomasMakan** [comment]
Finálny návrh:
![Navody digital final](https://user-images.githubusercontent.com/53820969/197342474-c3a35280-d18c-4e2f-a533-d76491f1e567.png)

Finálny text:  Jednoduché návody ako vybaviť úradné záležitosti

**Comment by jsuchal** [comment]
@TomasMakan ty si spoko ako to nakoniec sa pretavilo do produ? pri ux ludoch neviem ci su aj grafici alebo nie.
