### ISSUE TITLE
Aktualna tema - backend 

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#288]
K tomuto treba spravit podporu na backende. Za mna by tam mal byt v admine moznost pridat nejaky global message (nadpis, text, on/off).

Aby sa toto dalo zobrazit (na kazdej podstranke je to vzdy rovnake)
https://github.com/slovensko-digital/navody-frontend/pull/111

Sluzi to ked chceme dat nejaky velky oznam.

**Comment by HanaBene** [comment]
@jsuchal podla mna to treba zobrazit iba na homepage. 

Do admina pridat moznost zapnut tuto feature, definovat nadpis, podnadpis, text buttonu a link kam to ma smerovat.

**Comment by jsuchal** [comment]
@HanaBene ok, tak prepinac off/local/global. Ja som uz na gov.uk videl ze to naozaj bolo vsade. To sa hodi na hackathony, volby atd.

**Comment by mortenko** [comment]
@jsuchal  @HanaBene  pozeral som PR na navody-frontend a pokial dobre vidim tak  to nie je este hotove minimalne ten commit co tam je nesedi s tym co asi chcete. Takze ako ?

**Comment by martyciz** [comment]
cca dev steps:

* create table settings with key, value, enabled
* seed with record "current_topic"
* add admin section
* on close use cookies.permanent to remember user decision to have it closed. Key is hash of record value, so if it updates, it become visible again.
