### ISSUE TITLE
Next link opravit umiestnenie

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#289]
Next link je posunuty

![Capture](https://user-images.githubusercontent.com/45393631/67845044-0f313b80-faff-11e9-877a-f603e2055493.PNG)

**Comment by jsuchal** [comment]
Uz je to lepsie ale stale to neni uplne ono (vertikalne zarovnanie)

![image](https://user-images.githubusercontent.com/26342/68482484-fda40e00-0239-11ea-959b-868af1f08c3e.png)

cc @filiplikavcan

**Comment by hah** [comment]
u mna to vyzera fixed uz
version:
macOS 10.15.2
browsery: Safari 13.0.4/ Brave 1.3.113 / Chromium 80.0.3964.0  
![image](https://user-images.githubusercontent.com/46223652/74157951-7dff5400-4c19-11ea-81d1-d7f596caa293.png)
