### ISSUE TITLE
Nezmyselna formulacia textu ziadosti pre vydanie hlasovacieho preukazu

### ISSUE THREAD

**Issue by andrejm** [slovensko-digital/navody.digital#305]
V poslednom kroku na [ziadosti o hlasovaci preukaz](https://navody.digital/aplikacie/parlamentne-volby/hlasovaci-preukaz) **Zaslanie žiadosti na úrad** pre volby 2020 sa vygeneruje e-mail s takouto formulaciou:

```
... žiadam o vydanie hlasovacieho preukazu pre voľby do parlamentných volieb 2020  ...
```

co je IMHO nezmysel a skor by sa tam hodilo

``` 
... žiadam o vydanie hlasovacieho preukazu pre voľby do Národnej rady SR 2020 ...
``` 

Formulaciu som nasiel v tychto dvoch fajloch: 

- app/views/apps/parliament_vote_app/application_forms/_from_slovakia_email_body.text.erb
- app/views/apps/parliament_vote_app/application_forms/_from_slovakia_authorized_person_email_body.text.erb

**Comment by HanaBene** [comment]
updatnute, dakujem.
