### ISSUE TITLE
App idea: zisti kam mas platit dan

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#310]
https://www.financnasprava.sk/sk/infoservis/platenie-dani#VseobecneInformaciePlatenieDane

**Comment by HanaBene** [comment]
tu si mas vyskladat podla navodu kam mas zaplatit dan.

**Comment by HanaBene** [comment]
možné rozšírenie aplikácie https://priznanie.digital/

**Comment by jsuchal** [comment]
Toto uz netreba fixli to priamo na FS.
