### ISSUE TITLE
Podstranka pre vsetky notifikacie

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#311]
Mohli by sme mat nejaku podstranku pre vsetky notifikacie, kde by sa clovek mohol prihlasit/odhlasit. Idealne to asi aj nejako kategorizovat. 

- [ ] vymysliet odkial na to budeme linkovat
- [x] budu tam naozaj vsetky?
- [ ] promo

cc @HanaBene

**Comment by HanaBene** [comment]
ak budeme mat kategorizovane navody na homepage, tak to moze byt logicky zatriedene rovnako.

**Comment by jsuchal** [comment]
NewsletterSubscription,VoteSubscription,CompanyNewsletterSubscription

tieto tri zatial. 

@HanaBene skusme prejst vsetky navody ci nevieme vymysliet nejake dalsie listy a aj pre skupiny co teraz nemame uplne pokryte navodmi.

**Comment by jsuchal** [comment]
SZCO, Cudzinci, Majitelia vozidiel?, Rodiny?,

**Comment by HanaBene** [comment]
mame:
global notifikacie
volby
podnikatelia

mozme mat este:
OZtka
SZCO
Cudzinci

**Comment by HanaBene** [comment]
Aktivujte si upozornenia na mail
Prihláste sa k odberu upozornení, aby vám neunikol dôležitý termín, povinnosť, či príležitosť.

**Comment by jsuchal** [comment]
@HanaBene toto je nahodene https://navody.digital/notifikacie staci doriesit promo a kde sa na to budeme odkazovat z webu.

**Comment by jsuchal** [comment]
Na mobile to nevyzera moc dobre tak som to skusil trosku skratit tie texty. 
![notifikacie_share_image_v2](https://user-images.githubusercontent.com/26342/70976084-8de03900-20ab-11ea-98aa-5fd0ea29aebd.jpg)
![navody digital_notifikacie(iPhone 5_SE)](https://user-images.githubusercontent.com/26342/70976100-9afd2800-20ab-11ea-842e-37a705562477.png)

**Comment by HanaBene** [comment]
Nemozme to v mobilnej verzii mat bez tych popisov?

**Comment by jsuchal** [comment]
@HanaBene tiez nie zly napad, ale aj tak musime tie texty skratit.
