### ISSUE TITLE
Disable message

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#315]
Ked mame v appkach disable nejaku moznost, 
popis preco je to disablovane zanika v tom, ze cele je to sede. 
bolo by mozno fajn mat to odlisene, ze to nie je len hint k moznosti, ale disable message
![targetprocess-screen-capture (18)](https://user-images.githubusercontent.com/45393631/70430501-3cb4c180-1a7b-11ea-8abe-d889b4f7e7c0.png)

**Comment by HanaBene** [comment]
mohlo by to byt spolocne v jednom dizajne s tymto komponentom https://github.com/slovensko-digital/navody.digital/issues/147 ktory ti odpocitava dni na vybavenie.

**Comment by HanaBene** [comment]
![targetprocess-screen-capture (21)](https://user-images.githubusercontent.com/45393631/70432211-02e5ba00-1a7f-11ea-876b-c450aae67eb6.png)
napriklad tu sa to hodi hned pod nadpis, nejake okno odlisene, kde sa ti bude pocitat cas a po termine tam bude nejaky regret messgae, ze too late.

**Comment by tajovic** [comment]
Co tak mat disabled inputy a ich label sedou a ostatne tmavou/ciernou?
![image](https://user-images.githubusercontent.com/11182227/70432754-42f96c80-1a80-11ea-95db-fd9015ebf854.png)

**Comment by tajovic** [comment]
Pripadne k mensiemu font-weight aj zmensit pismo popisu.
![image](https://user-images.githubusercontent.com/11182227/70432819-72a87480-1a80-11ea-9fb7-70b36f6d0006.png)

**Comment by tajovic** [comment]
Z UI pohladu mozu byt niektore moznosti identicke, z pohladu pouzivatelov (a UX) to tak byt nemusi. Treba rozlisovat kedy pouzivatel dostava alternativy jednej akcie (ziskat hlasovaci preukaz postou, osobne, cez delegata) alebo sa snazime pouzivatelov rozdelit do roznych kategorii (je domaci, je zahranicny). 

V prvom pripade sa 100% pouzivatelov na obrazovke moze rozhodnut, ktoru moznost si zvoli a aj v pripade, ze su vsetky okrem jednej neaktivne (disablnute) moze stale 100% pouzivatelov zvolit poslednu aktivnu moznost a ist nou. V takomto pripade je podla mna v poriadku zneaktivnit moznosti, ktore uz nie su relevantne. 

V druhom pripade sa pouzivatelia rozdiela medzi jednotlive skupiny prave na zaklade moznosti a ak sa nejaka z nich zneaktivny (disablne), urcite percento pouzivatelov nema ako pokracovat a su ukrateny o ferove vysvetlenie. V takomto pripade treba vsetky moznosti drzat aktivne a radsej pouzivatelovy vysvetlit, ze uz to nie je mozne az po tom co sa dostane na dalsiu obrazovku, tj. po tom, co uz je jasne do akej skupiny patri. Aj ked tam nebude mat dalsiu akciu minimalne tam bude mat podrobne vysvetlenie. V tejto situacii totizto pouzivatel nemoze zvolit inu aktivnu moznost, ak je ta jeho nekativna. Ak je raz bez trvaleho bydliska, nemoze zvolit ze ho ma ked je jeho moznost neaktivne. Jeho "zivot" sa teda stava neaktivnym ak nebude prenho mozne zvolit si moznost, ktora je prenho pravdiva. A to je pre UX problematicke.

**Comment by TomasMakan** [comment]
Tu ale pozor na kontrast. aj disabled by som mal vedieť prečítať
https://webaim.org/resources/contrastchecker/
