### ISSUE TITLE
feedback url zmenit

### ISSUE THREAD

**Issue by MiroBabic** [slovensko-digital/navody.digital#32]
feedbacky pri footeri posielaju zatial na nejake custom url formulare, treba vyrobit google forms a zmenit url v kode
application.html.erb
 <form id="autoform-form-1">
 <form id="autoform-form-2">
 <form id="autoform-form-3">

**Comment by alhafoudh** [comment]
@jsuchal urobis google form pod slovensko.digital? urobim potom tuto zmenu

**Comment by jsuchal** [comment]
Tuto treba este pockat kym frontendist (cc @filiplikavcan) dorobia cely ten form tak ako ma byt. Potom to prehodime.

**Comment by jsuchal** [comment]
Toto je duplikat #18 zatvaram.
