### ISSUE TITLE
Aplikacia volby: doladit field meno priezvisko

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#322]
Mame tam: 
Meno, priezvisko, titul
hint:
_Ako na občianskom preukaze. Napríklad: JUDr. Ján Mrvička_

Nesedi forma v nazve fieldu a v hinte + na obciansom nie su informacie v tomto tvare, titul je na druhej strane. 
Riesenim je preformulovat hint na _Napríklad: Ján Mrkvička, JUDr._ vynechat cast o obvianskom

**Comment by JanHamara** [comment]
S radostou to spravim, ako je mozne dostat sa k repu webstranky?

**Comment by jsuchal** [comment]
Repo je predsa toto presne tu.

**Comment by JanHamara** [comment]
Samozrejme ze je, sorry hlupa otazka 😆 myslel som si ze tu je iba slovensko.digital, nie navody.digital 👍

**Comment by jsuchal** [comment]
Toto bolo podla mna divne, ved titul sa pise niekedy pred menom a niekedy za menom. Nemal to byt predpis ze kde co napisat.
