### ISSUE TITLE
Markup pre navody

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#324]
https://gds.blog.gov.uk/2019/12/19/making-gov-uk-more-than-a-website/

@HanaBene toto je mala zmena a super vysledok, toto chceme!

**Comment by crutch** [comment]
Dalsie schema.org typy, ktore som nasiel na gov.uk

- Article, https://www.gov.uk/vehicles-can-drive?step-by-step-nav=e01e924b-9c7c-4c71-8241-66a575c2f61f, google zobrazuje `articleBody`
![image](https://user-images.githubusercontent.com/119724/74085157-650a6d80-4a76-11ea-953c-bf587f1b74d1.png)

- FAQPage, https://www.gov.uk/legal-obligations-drivers-riders?step-by-step-nav=e01e924b-9c7c-4c71-8241-66a575c2f61f, google zobrazuje `acceptedAnswer`
![image](https://user-images.githubusercontent.com/119724/74085172-95520c00-4a76-11ea-95a2-4b70139faf9d.png)

- GovernmentService, https://www.gov.uk/book-theory-test?step-by-step-nav=e01e924b-9c7c-4c71-8241-66a575c2f61f, su tam nejake `isRelatedTo`, ale google zobrazuje aj vselico ine
![image](https://user-images.githubusercontent.com/119724/74085210-16110800-4a77-11ea-9797-1bf0730f210d.png)
