### ISSUE TITLE
Príspevok pri narodení dieťaťa

### ISSUE THREAD

**Issue by devdanco** [slovensko-digital/navody.digital#332]
Teraz v january som vybavoval prispevok na dieta a kusok sa pomenili veci a este nie su ani aktualizovane.

- vyhlasenie o bydlisku ktore je na nete je stare a bohuzial nie je nikde zavesene dostanete ho len na urade prace zatial
- treba doniest aj karticku s cislom uctu alebo zmluvu o uzatvoreni uctu s bankou aby mohli skontrolovat IBAN
- treba vyplnit este tieto dva papiere:
[Cestne vyhlasenie](https://www.upsvr.gov.sk/buxus/docs//SSVaR/tlaciva/NOVE_Cestne_vyhlasenie_k_prispevku_pri_narodeni_dietata.pdf)
[Poucenie](https://www.upsvr.gov.sk/buxus/docs/SSVaR/tlaciva/Poucenie_pre_obcana_ziadajuceho_o_SSD.pdf)

**Comment by jsuchal** [comment]
@devdanco diky za report, @HanaBene sa na to pozrie ked si najde chvilu.

**Comment by jsuchal** [comment]
@PetraPlesnikova toto mame vyriesene ci nie?

**Comment by HanaBene** [comment]
Ahojte, ja som to riesila v 2021 a moje postrehy:
_vyhlasenie o bydlisku ktore je na nete je stare a bohuzial nie je nikde zavesene dostanete ho len na urade prace zatial_
toto som mala tlacivo co mame na navodoch, nebol problem
_treba doniest aj karticku s cislom uctu alebo zmluvu o uzatvoreni uctu s bankou aby mohli skontrolovat IBAN_
toto odomna nechceli, zavisi zrejme od konkretnej samospravy
_treba vyplnit este tieto dva papiere:
[Cestne vyhlasenie](https://www.upsvr.gov.sk/buxus/docs//SSVaR/tlaciva/NOVE_Cestne_vyhlasenie_k_prispevku_pri_narodeni_dietata.pdf)_
tento krok v navode je
_[Poucenie](https://www.upsvr.gov.sk/buxus/docs/SSVaR/tlaciva/Poucenie_pre_obcana_ziadajuceho_o_SSD.pdf)_
tento nemame, toto treba overit, pridat.

**Comment by HanaBene** [comment]
UPDATE: 
mame testovaca, budu vysledky buduci tyzden, upravim nasledne

**Comment by jsuchal** [comment]
@HanaBene mame nejaky update tuto? Rad by som to tu upratal. Ak to nie je aktualne uz tak zatvor pls

**Comment by HanaBene** [comment]
podla posledneho testovania sedelo. asi zavisi aj od konkretneho uradu. 
zatvaram teraz, ked sa najde novy adept na testovanie, prejdeme znova
