### ISSUE TITLE
Volby.digital: bodka za emailom 

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#346]
pri buducich volbach preformulovat text tak, aby nebola bodka za emailovou adresou na obec.
mame feedback, ze sa to tazko potom kopiruje, hlasi to nespravnu adresu, ked to ludia skopiruju aj s tou bodkou na konci.

**Comment by himak** [comment]
A kde presne to je ? Nejaky screen. Vdaka

**Comment by HanaBene** [comment]
toto je k aplikacii volby.digital, nie je to momentalne aktualne.
