### ISSUE TITLE
newsletter prihlasovanie - ked je na vyber iba jeden list, nezobrazovat checkbox

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#348]
situacia: mame prihlasenie do newslettra formou ze v okne oznacis checkboxy, ktore kategorie ta zaujimaju (podnikatelia, rodina, auto, vseobecny..)
ked je na vyber iba jedna kategoria aj tak to musis zaciarknut. 

uprava: ak je tam len jeden, schovat checkbox a  popis, alebo pridat nejaky atribut, aby sa to dalo zapnut/vypnut
![capture (3)](https://user-images.githubusercontent.com/45393631/76954664-01931b80-6911-11ea-9f22-fb5f95bc6686.png)
![targetprocess-screen-capture (53)](https://user-images.githubusercontent.com/45393631/76954778-3606d780-6911-11ea-9da7-fb57bf81c4a5.png)

**Comment by HanaBene** [comment]
@jsuchal moze toto @michalrohacek256?

**Comment by jsuchal** [comment]
Jasné.
