### ISSUE TITLE
Duplikovanie elementov pri pouziti history.goBack()

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/navody.digital#350]
![image](https://user-images.githubusercontent.com/1194439/78344349-8aaa8380-759c-11ea-96e1-deac110ce740.png)

Ked sa pri navigacii na homepage pouzijem tlacitko back tak mi kazdy krat ked idem naspat pribudne jeden button Rozbalit vsetko.

**Comment by jsuchal** [comment]
@filiplikavcan toto je kvoli tomu ako funguje turbolinks. Predpokladam, ze toto je zavesene na nejaky event kde sa to inicializuje. Asi to treba nejako lepsie vymysliet. https://github.com/turbolinks/turbolinks#full-list-of-events

@eronisko nepamatas si ako sme to riesili?

**Comment by janmacek** [comment]
Skusal som sa pohrat s tym suborom application.js, podarilo sa mi docielit aby to tam dalo iba jeden ten element, ale potom po tlacitku back nefunguje, strati sa ten eventListener nejako (tie sa asi necachuju). Myslim si ze s abude treba pozriet na navody.digital\node_modules\navody-digital-frontend\all.js#798 a tam to kontrolovat.

Kod kt. odstrani iba problem duplicity:
``` 
(function() {
    var navody_digital_loaded = false;
    document.addEventListener('turbolinks:load', function () {
        if (!navody_digital_loaded) {
            // Initialize GovUK/Navody-frontend Javascript

            initAll();
            navody_digital_loaded = true;
        }
    });
})(); 
```

**Comment by janmacek** [comment]
Pripravil som workaround pre tento problem. Spominane duplikovanie je odstranene ale podobna chyba sa moze prejavovat aj inde, takze by bolo treba pripravit globalne riesenie, to sa ale musi opravit v 'navody-digital-frontend' a to uplne neviem odkial sa tam berie ten kod.

**Comment by jsuchal** [comment]
@celuchmarek over toto pls.
