### ISSUE TITLE
Feedback spam filter

### ISSUE THREAD

**Issue by michal-rohacek** [slovensko-digital/navody.digital#352]
pridat captcha ochranu na feedback bar dole na stranke, aby nam nechodil spam od robotov.

**Comment by jsuchal** [comment]
Ja len, ze ci to je nutne aj pre pozitivnu spatnu vazbu.

**Comment by jsuchal** [comment]
@HanaBene za mna to upravme tak, ze do GA odpalime event hned ako klikne clovek ano/nie/spatnu vazbu a nasledne captcha len tam kde sa posiela text. (cize feedback/nie).

**Comment by HanaBene** [comment]
@jsuchal tie kliknutia Useful potom nechodia z automatu? Nebudeme mat potom nerealnu vzorku useful/not useful?

**Comment by jsuchal** [comment]
No nereálne je podľa mňa čakať že niekto bude riešiť captcha kvôli tomu aby nám klikom poďakoval. Porovnávať pomer useful a not sa nedá už ani teraz lebo jedno chce text a druhé nie. Čiže porovnanie bude len naprieč stránkami a tam to nevadí

**Comment by jsuchal** [comment]
@michal-rohacek vies pls na tej pozitivnej spatnej vazba zrusit tu captcha?

**Comment by michal-rohacek** [comment]
@jsuchal ok

**Comment by michal-rohacek** [comment]
hotovo
