### ISSUE TITLE
Upravit FAQ 

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#365]
Upravena verzia: 
https://docs.google.com/spreadsheets/d/1nuox6d1hW8zlL7Q8LPbLSlaGA-23eLZyn_Tdq0qGCcM/edit?usp=sharing

**Comment by jsuchal** [comment]
@HanaBene toto je potrebne len v admine upravit obsah?

**Comment by HanaBene** [comment]
ano, uloha asi pre Petu.

**Comment by PetraPlesnikova** [comment]
sekcia FAQ je updatnuta podla prilozeneho Excelu, ak do buducna prideme s navrhom na doplnenie dalsich otazok-odpovedi, tak pridam.
P.
