### ISSUE TITLE
Rozbehat code coverage na code climate

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#37]

**Comment by alhafoudh** [comment]
@jsuchal pred zavedenim codeclimate, navrhujem rozbehat rubocop a pofixovat veci. co povies? mame taky rozumny config ktory pouzivame u klientov

**Comment by jsuchal** [comment]
No nie som uplne fanusik rubocop lebo vacsinou mi to pride ako bikeshedding, ale mozno som len zvyknuty, ze sa to, ze take banalne problemy proste v PRs nemame a neriesime. V klude to vsak sem dajme a ked nam tento grammar nazi as a service zacne liezt na nervy tak to vypneme :)

**Comment by alhafoudh** [comment]
Ok, tak skusme to dat na codeclimate. Uvidime potom co nam povie :)

**Comment by jsuchal** [comment]
codeclimate rozbehany je, toto je skor issue na code coverage.

**Comment by jsuchal** [comment]
Test coverage rozbehany.
