### ISSUE TITLE
Linkovat podanie dane z nehnutelnosti priamo

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/navody.digital#390]
Na https://navody.digital/zivotne-situacie/kupa-bytu/krok/prihlasenie-sa-k-dani-z-nehnutelnosti 
by sme mozno mohli odkazovat priamo na 
https://www.slovensko.sk/sk/detail-sluzby?externalCode=sluzba_egov_212

**Comment by jsuchal** [comment]
Fixed.
