### ISSUE TITLE
Ako support chcem vediet, ked nam niekto napise nieco do formulara

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#391]
Momentalne do formulara dole (klikni na "NIE" alebo "napiste nam") sem tam niekto napise. Ide to do google form a odtial divnym procesom k nam. Bolo by dobre, aby nam to posielalo na normalny support email (navody@slovensko.digital) s reply-to (user co to poslal)

![image](https://user-images.githubusercontent.com/26342/104939232-73fcde00-59b0-11eb-8e93-9f8d6f60c61c.png)

Taktiez asi ta recaptcha pre prihlaseneho usera nema zmysel (ze @michal-rohacek)

**Comment by michal-rohacek** [comment]
jasne, pre lognuteho usera ju tam netreba.

**Comment by JMatej** [comment]
@jsuchal tak tym padom ja zoberiem toto

**Comment by jsuchal** [comment]
Toto sa riesi tu inak. https://github.com/slovensko-digital/navody.digital/pull/426
