### ISSUE TITLE
Generovat slug automaticky

### ISSUE THREAD

**Issue by michal-rohacek** [slovensko-digital/navody.digital#392]
slug sa zadava rucne pricom by sa mohol autogenerovat z nazvu. pokial teda nevieme o nejakych pripadoch, kedy je to neziaduce.. pre take by tam mohol byt checkbox trebars.

**Comment by lukas-manduch** [comment]
Alebo tu musim nieco napisat 😀

**Comment by jsuchal** [comment]
@lukas-manduch long time no see. Ako sa dari s tymto?

**Comment by celuchmarek** [comment]
@jsuchal V #473 sa to vyriešilo tak, že ak slug input field pri vytváraní ostane prázdny, vygeneruje sa automaticky, inak sa použije zadaný. Nie je o tom ale v adminovi žiadna zmienka a človek tak zo zvyku bude naďalej vymýšľať vlastné slugy. Osobne by som k tým text inputom doplnil aspoň hint, že slug sa automaticky vygeneruje, ak ho necháš prázdny. Prípadne sa dá ísť až do nejakého explicitného checkboxu, že chcem použiť vlastný slug.

Ak nechceme pridávať takúto kozmetickú vec, issue je closed.

**Comment by jsuchal** [comment]
Toto asi staci nateraz takto.
