### ISSUE TITLE
Typy NotificationSubscription su hardcoded v modeli

### ISSUE THREAD

**Issue by michal-rohacek** [slovensko-digital/navody.digital#393]
tieto typy sa daju pouzit cez admina v ramci custom componentu v description navodu, co moze byt flexibilne, nanestastie nove typy treba aj nahardkodit do modelu NotificationSubscription (potom sa validuju voci tomuto zoznamu)

ak chceme ponechat whitelist validaciu kvoli security, mozno by stacilo presunut takyto ciselnik do DB, kde by sa mohli pridavat nove typy bez nutnosti zasahu do kodu a deployov

**Comment by jsuchal** [comment]
Toto dava zmysel len pre subscriptions, ktore maju prinajlepsom nejaky sendinblue list. Ziadnu vacsiu logiku tam bez zasahu do kodu nepridame. Kedze zoznamy ich pridavame velmi sporadicky, toto zatial zatvaram.
