### ISSUE TITLE
Ako používateľ chcem vidieť zoznam FAQ

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#4]
Na uvodnej stranke #2  chcem vidiet FAQ. Zoznam a poradie asi niekde v konfiguraku / db.

**Comment by alhafoudh** [comment]
@jsuchal toto je done, nie?

**Comment by jsuchal** [comment]
Funkcne asi ano, dizajnovo by som povedal, ze este nie.

**Comment by eronisko** [comment]
Fixnute v b613e6884a02a12c47c13d54184f912e2ffc3ba7
