### ISSUE TITLE
Ako používateľ chcem byť upozornený že už mám rozpracovanú totožnú životnú situáciu

### ISSUE THREAD

**Issue by alhafoudh** [slovensko-digital/navody.digital#43]
- kliknem na zivnostnu situaciu
- okrem buttonu "Začať" by tam mohol podmienene byt button "Pokračovat"
- po kliknuti na "Pokračovať" sa otvori existujuca user journey

**Comment by jsuchal** [comment]
Povodna idea bola presne takato, ked si prihlaseny, tak tam budes vidiet vsetky rozpracovane k tej ZS.

**Comment by alhafoudh** [comment]
Duplikat #15
