### ISSUE TITLE
Pridanie "Super Destroy" button

### ISSUE THREAD

**Issue by michal-rohacek** [slovensko-digital/navody.digital#441]
Pri upravach navodov sa nam niekedy stane, ze chceme vymazat cely task zo stredu navodu. V tomto scenari mozu nastat 2 problemy:
- task sa nepodari vymazat - v pripade, ze existuju useri, ktori maju tento task prave rozpracovany - teda stale existuje foreign key reference (UserTask) - zistit ci podobny scenar moze fungovat aj pri inych dvojiciach okrem Task - UserTask
- v pripade, ze sa aj podari vymazat task, treba ostatne tasky repositionovat rucne (mari sa mi nejake `reposition_tasks` )

Idea: vytvorit na to cosi ako "super destroy" / "kill" button, ktory pripadne komplikacie vhodne vyriesi sam.

cc @PetraPlesnikova

**Comment by jsuchal** [comment]
Toto si myslim, ze by sme vlastne nemali dovolit, aby sa dialo lebo co ludia co maju rozpracovane tie navody? uplne im to pokazime (+ akonahle na to budu naviazane notifications tak to je este horsie). 

Ak sa toto deje na stagingu, tak chapem, na prode by som skor siel cestou, ze stare rozpracovane nechytene po nejakom pol roku zrusime (s notifikaciou userovi). 

Jedine kde toto moze asi nastat mi pride nejake prechodne obdobie zmeny legislativy ze sa krok vypusta a my tam este mame podania co idu po starom.

**Comment by jsuchal** [comment]
#282 je duplicita a uz vyriesene.
