### ISSUE TITLE
Zivotna situacia: Eurovolby 2019

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#46]
Toto by mohol byt celkom pekny a lahky navod. https://platforma.slovensko.digital/t/eurovolby-2019/5951

**Comment by HanaBene** [comment]
Tento navod chceme pouzit ako PR k Public spusteniu.

**Comment by jsuchal** [comment]
@HanaBene zda sa ze hotovo, este obrazky na share a bude to.
