### ISSUE TITLE
Sitemapa nefunguje - 404

### ISSUE THREAD

**Issue by alhafoudh** [slovensko-digital/navody.digital#486]
Sitemapa uvedena v https://navody.digital/robots.txt nefunguje (https://navody.digital/sitemaps/sitemap.xml.gz), odpoveda HTTP 404.

**Comment by alhafoudh** [comment]
Podla vsetkeho staci iba v pocas deployu spustit `rails runner config/sitemap.rb`

**Comment by jsuchal** [comment]
@alhafoudh s tymto mas skusenost? ja by som to asi najradsej hodil na s3 pri deploy nech sa to generuje alebo kazdy den regenereate

**Comment by alhafoudh** [comment]
@jsuchal ano, ale to robit tak, ze clockwork pravidelne, moze byt?

**Comment by jsuchal** [comment]
Jo pravda.

**Comment by jsuchal** [comment]
@alhafoudh beries si toto ty teda?

**Comment by alhafoudh** [comment]
Ano ano :)
