### ISSUE TITLE
Pridať ku návodom akých zákonov sa týkajú

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/navody.digital#487]
Ak by bola informácia akých zákonov sa týkajú návody dalo by sa automaticky označovať návody za zastarané (podľa dátumu zmeny v slov-lex), alebo aspoň upozorniť že je dobré si skontrolovať zmeny v zákone.

Asi sa oplatí aspoň začať zbierať dáta vo forme linkov na slov-lex priradených ku návodom

**Comment by TomasMakan** [comment]
Ako by malo fungovať to automatické označovanie podľa dátumu zmeny?

**Comment by pomali** [comment]
Ak by sme mali navod napisany podla [403/2021 Z. z.](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2021/403/20211201.html)(01.12.2021 - 16.07.2022 (neznamy v case vytvorenia navody)) tak vieme povedat, ze nastala nejaka zmena a vieme na to upozornit cloveka.

Ak by sme chceli mat vasci detail tak by sme mohli naliknovat presne paragrafy+odseky a pozriet ci v novele je zmena tych casti napr https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2003/530/20211201.html#paragraf-7.odsek-19 a napisat ze tieto relevantne zmeny sme nasli (mozno su tam aj dalsie).

**Comment by jsuchal** [comment]
Suhlas, ze v prvom kroku staci nejaky notify co nam len posle ping / email / slack spravu, ze sa zmenilo nieco v zakone ktory mame pouzity v navode. Ono je to trochu tricky lebo zakony sa bezne upravuju aj inymi zakonmi ale v konsolidovanom zneni by to vidiet byt malo.
