### ISSUE TITLE
Potrebujeme texty na prihlasenie cez EID/SVM

### ISSUE THREAD

**Issue by alhafoudh** [slovensko-digital/navody.digital#488]
Potrebujeme 2 texty:

1. Ked uzivatel este nema EID priradenu k uctu, potrebujeme ho vyzvat aby zadal email aby sme mu zaslali specialnu linku, ktora potvrdi priradenie EID k uctu.

Takto priblizne vyzera ta stranka s vyzvou na email:

<img width="1295" alt="Screenshot 2022-06-24 at 18 23 05" src="https://user-images.githubusercontent.com/43397/175577598-cc1fbe56-9b99-4d30-a78f-8af207713167.png">

2. Text emailu, kde je potvrdzujuca linka

<img width="651" alt="Screenshot 2022-06-24 at 18 23 30" src="https://user-images.githubusercontent.com/43397/175577586-c183b8a1-3711-45d2-ad87-dc4b0815387d.png">

**Comment by jsuchal** [comment]
@alhafoudh aby sme nezabudli
- potrbeujeme pridat jasne, ze "Vitaj, jan suchal, prihlasenie cez eid bolo uspesne"
- aby si mohol pokracovat zadaj este email, kde ti posleme email na jednorazove overenie 
- a dole button, ze "nechcem pokracovat, chcem sa odhlasit"

**Comment by alhafoudh** [comment]
@jsuchal tato textacia tam je az na ten button, upravim ho a upratnem PR
