### ISSUE TITLE
Vyhľadávanie: Ako používateľ chcem vedieť vyhľadať životnú situáciu / podanie / otázku

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#5]
Pre uvodnu stranku #2 

- Mali by sme zaindexovať zivotne situacie, podania, otázky (FAQ) a vo vyhľadávaní zobrazovať to najlepšie čo vieme. 
  - Pri prekliku na podanie sa zobrazí ten krok životnej situácie. (Niektoré kroky/podania mozu byt vo viacerých ZS)
- ~~Chýba nám podstránka výsledkov vyhľadávania (zatiaľ non issue kedže návodov bude asi málo.~~ #25

**Comment by eronisko** [comment]
Podstranka vysledkov: #25
