### ISSUE TITLE
Indexing problem

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#506]
![image](https://user-images.githubusercontent.com/26342/189600474-36666c6f-ce2d-4801-ab98-860784683585.png)

Toto sa deje a neviem uplne preco. Mame stare pages v sitemap? alebo unpublished? @alhafoudh kuknes?

**Comment by alhafoudh** [comment]
@jsuchal jasne, das mi pristup do `/admin`?

**Comment by jsuchal** [comment]
Vyzera, ze fixnute
