### ISSUE TITLE
logovanie eventov v návode/apke "zápis identifikátorov do ORSR"

### ISSUE THREAD

**Issue by PetraPlesnikova** [slovensko-digital/navody.digital#508]
bude zaujímavé a potrebné pre komunikáciu/média atď. vedieť čísla používania návodu a apky. Bolo by preto super vedieť nejaké zaujímavé z nich interpretovať, napr.:
- **koľko ľudí si stiahlo XMLko, resp. dalo poslať na email?** - ak by sme prípadne vedeli aj toto vidieť, možno by sme mali odpoveď na to, či si ľudia sťahujú, alebo posielajú na email (ale asi vždy budeme chcieť mať pre ľudí dostupné obe možnosti, takže asi skôr len zo zaujímavosti toto:)
- koľko ľudí kliklo v návode na zelený button **Pripraviť podanie pre s.r.o.**
- koľko ľudí preplo v appke na "Cudzinec"? Vedeli by sme si potvrdiť, že predvýber možnosti "Občan SR" bola dobrá feature
- potom klasické veci ako asi bude vidieť na Plausible - koľko ľudí prišlo na ktorý bod návodu/apky, to podla urlky.
Zaujímavé sú tie čísla, ktorí ľudia to celé prešli dokonca a skončili už spomínaným stiahnutím XML alebo poslaním na email.

**Comment by jsuchal** [comment]
@luciajanikova tuto by bolo fajn asi odpalit nejake eventy ked sa z centraly odosielaju data - aby sme vedeli kolko sa toho poslalo. Lucia pristup do plausible som ti spravil.

**Comment by PetraPlesnikova** [comment]
dala som viacero návrhov a popisov, ale pokojne si vyberme aj že 1-2 najzaujímavejšie, na ktorých to bude dobre vidieť a my budeme vedieť interpretovať.

**Comment by jsuchal** [comment]
@luciajanikova tu su nejake dalsie veci na logovanie.

**Comment by jsuchal** [comment]
@luciajanikova toto uz mame nie?
