### ISSUE TITLE
Svadba zdravotna poistovna

### ISSUE THREAD

**Issue by MarekVigas** [slovensko-digital/navody.digital#521]
Z textu v navode pre svadbu nie je uplne jasne ze zmenu do zdravotnej poistovne nie je taktiez nutne nahlasovat. 
Aspon v pripade VSZP si taktiez tieto udaje nacitaju z registra fyzickych osob. Zaroven nie je nutne si vybavovat novy preukaz poistenca kedze OP s cipom nahradza preukaz poistenca. V poistovni odporucaju si vymenit europsky preukaz poistenca. 
![image](https://user-images.githubusercontent.com/11539820/191517457-e2cf664e-d52b-4bc9-a308-be5a53094c46.png)

**Comment by HanaBene** [comment]
upravila som text podla vyssie popisaneho a podla vlastnych nedavnych skusenosti https://navody.digital/zivotne-situacie/svadba/krok/vymenit-doklady-pri-zmene%20mena
