### ISSUE TITLE
Oddelenie primarnych akcii od bonus akcii pri podani

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#525]
Momentalne sa pri podani rozbrazuju subscriptions spolu co je dark pattern a bolo by dobre to spravit trosku slusnejsie. Cize oddelit primarne veci od sekundarnych.

Navrh 
![image](https://user-images.githubusercontent.com/26342/197026129-fde11961-a681-47a0-92c9-6b3c0b0ca50e.png)

**Comment by crutch** [comment]
Je v mastrovi, https://github.com/slovensko-digital/navody.digital/commit/4ee5198df765855058b76904a9357ac545c2b482
