### ISSUE TITLE
Obsah kategorii na homepage

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#539]
![Screenshot_20221023_161026](https://user-images.githubusercontent.com/45393631/197396999-c036b5f5-588c-4c1d-96ad-a41972513d28.jpg)
Na home mame v kategoriach textovy popis. Ked bude pribudat obsah, prestane to sediet. 
Vhodnejsie je tam vymenovat naavody patriace do kategorie (asi max 3, resp. podla max dlzky popisu), oddelene ciarkami napriklad.
Nice to have.

**Comment by celuchmarek** [comment]
Ja si myslím, že bude lepšie časom manuálne upravovať tie popisy a nenastavovať to nejako strojovo. Človek musí vyhodnotiť, ktoré tri návody budú najlepšie reprezentovať kategóriu, prípadne zvoliť trochu iný popis. A napr k prepisu vozidla máme "... kupujúci" a "... predávajúci" a ďalšie podobné výnimky.

**Comment by HanaBene** [comment]
Okej, upravime ked bude potreba
