### ISSUE TITLE
Zobrazovanie pages na homepage

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#540]
Po novom mame kategorizovane navody a dostali sme sa do situacie, kedy nemame ako zobrazit Pages. 
Viem ich vyhladat, mozu byt v top navodoch, ale inak zobrazene nie su. 
Napriklad Moznosti elektronickej komunikacie je vec, co asi chceme mat zaradene niekde, kde by to bolo vidno.  
Dalo by sa to zobrazit po kliknuti na kategoriu? 

Pripadne potom treba vymysliet, kam by bolo dobre to vytiahnut. FAQs? Ako mozem komunikovat elektronicky a tam bude link na ten clanok? 

@jsuchal thoughts?

**Comment by jsuchal** [comment]
@celuchmarek toto asi nieco robime zle nie? Mali mat moznost zaradovat do kategorii app, journey, page

**Comment by HanaBene** [comment]
EDIT: Musime nastavit Featured este, potom sa zobrazia aj Pages.
