### ISSUE TITLE
Ziadost o kopiu listin v zbierke listin ORSR - neosetreny prazdny stav

### ISSUE THREAD

**Issue by crutch** [slovensko-digital/navody.digital#542]
Myslel som si, ze tymto navodom 

https://navody.digital/aplikacie/or-sr-listiny/vyplnenie

sa dostanem k digitalnej analogii (heh) notarom osvedceneho vypisu z ORSR.

Asi na to ten navod nie je, navyse nema v implementacii dobre osetreny stav, ked spolocnost nema ziadnu listinu (aspon si myslim, ze toto je problem).

https://user-images.githubusercontent.com/119724/204619190-f570f791-5011-4888-894b-a10e74997ee8.mov

**Comment by jsuchal** [comment]
Na výpis treba ísť na rpo.statistics.sk a prihlásiť sa Eid/svm

**Comment by crutch** [comment]
Dik. Mozno by teda aj ten opis navodu mohol byt lepsi, aby ludia vedeli, ze vypis nie je listina.

Pride mi ta veta, co tam je taka nejaka pokrivena:

> Táto aplikácia Vám umožní podať žiadosť o vyhotovenie kópie listiny uloženej v zákonom ustanovených listín obchodného registra na pár klikov.

**Comment by luciajanikova** [comment]
Fun fact: Ani v sluzbe na slovensko.sk toto nemaju moc dobre podchytene😄

Pridala by som view pre spolocnosti, ktore nemaju ziadne listiny, nieco taketo asi:
![image](https://user-images.githubusercontent.com/43437253/205677230-d3899abd-81f2-40b9-9fec-fdc015130029.png)
@jsuchal, @HanaBene prosim feedback

**Comment by jsuchal** [comment]
@luciajanikova toto je ok, ale chyba mi nejaky "now what?" text. Co to vlastne znamena, kedy sa to deje a co mozem spravit?

**Comment by luciajanikova** [comment]
@jsuchal a mame taketo info alebo ako vieme zistit?

**Comment by jsuchal** [comment]
@luciajanikova asi len od pravnika. Pingam ho na slacku.

**Comment by LegalEngineering** [comment]
@luciajanikova @jsuchal skúsim to rovno sformulovať ako text na web. "Pre zvolenú spoločnosť sme nenašli žiadne digitalizované listiny, tieto však môžu existovať v listinnej podobe. Vyžiadajte si sprístupnenie/zdigitalizovanie požadovaných listín mailom, príp. iným podaním na súde, ktorý vedie obchodný register, v ktorom je požadovaná spoločnosť zapísaná. Kontakty nájdete tu https://obcan.justice.sk/infosud/-/infosud/zoznam/sud"

**Comment by LegalEngineering** [comment]
Pre úplnosť - obdobný text by som zvážil pridať aj k dopytom, ktoré boli úspešné. Lebo v zozname listín vám to vyhodí len tie, ktoré sú digitalizované; pritom k dispozícii môžu byť aj listinné. Často "idem" po konkrétnej listine, ktorú ale cez túto službu nevidím, ergo ju nie je možné vyžiadať. Spravidla potom píšem na príslušný súd a relatívne rýchlo zdigitalizujú tú listinu a spravidla sa tam objavia aj ďalšie dokumenty. [Zo zákona by mali byť do elektronickej podoby preklopené komplet zbierky listín](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2003/530/20160101.html?ucinnost=15.12.2022#paragraf-12.odsek-11), ale tak well... sme na slovensku.

Pre úplnosť možno ešte k výsledkom hľadania pridať aj nejak rozumne napísané poučenie, čo všetko by v zbierke listín malo byť, a ak to chýba, treba si to rovnako vyžiadať -[ link na zákonný obsah zbierky listín](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/2003/530/20160101.html?ucinnost=15.12.2022#paragraf-3).

**Comment by jsuchal** [comment]
@luciajanikova toto je super, skusme toto zaradit na hackathon v marci.

**Comment by luciajanikova** [comment]
![image](https://user-images.githubusercontent.com/43437253/227708687-14e76f30-f61e-4bca-befd-929cbc0fc59a.png)
@jsuchal takto moze byt?

**Comment by luciajanikova** [comment]
A info aj pri najdenych listinach: 
![image](https://user-images.githubusercontent.com/43437253/227709233-95f20075-ddcf-41e2-9713-e7193d1b587a.png)
@jsuchal

**Comment by jsuchal** [comment]
@luciajanikova blank stav je ok. ale ten warning je prilis dlhy. Druhy odstavec by som dal len jednou vetou "Ak potrebujete listinu, ktora este nebola zdigitalizovana kontaktujte sud ..."

**Comment by luciajanikova** [comment]
![image](https://user-images.githubusercontent.com/43437253/227734792-45508ccd-a5c4-4393-81f1-65f9669bded0.png)
takto @jsuchal ?

**Comment by LegalEngineering** [comment]
> Na výpis treba ísť na rpo.statistics.sk a prihlásiť sa Eid/svm

Je na to služba [aj na ÚPVS.](https://www.slovensko.sk/sk/detail-sluzby?externalCode=ks_340705) (tip: keď sa podanie nepodpíše, výpis dojde ihneď; inak to trvá nejaký čas kým sa overí podpis)

**Comment by jsuchal** [comment]
@LegalEngineering toto je dobra info. Skoda vsak, ze to chodi len to schranky. z RPO to poslu aj na email cize to by sa dalo pouzit lepsie (ale tam opat zase je iny problem - nemaju integraciu na sk.sk)

**Comment by LegalEngineering** [comment]
@jsuchal ale môže to dôjsť do hocijakej, keby z toho mala byť služba tak by sa to dalo nastaviť tak, že request sa bude zasielať napr. zo schránky slovensko.digital, kam aj dôjde výsledok a ten nejak magicky cez govbox pošlete užívateľovi? Asi by to chcelo aj za nejaké feečko... 

Keby bol nad rámec toho záujem o nadstavbu, že z toho spravím zaručenú konverziu a pošlem to niekomu listinne, prípadne sa po to zastaví, dá sa nad tým zamyslieť. (aj keď tento usecase dostatočne obsluhuje samotná služba na slovensko.sk, keďže ten výpis sa dá vyžiadať aj v listinnej podobe... Akurát som ju nikdy nevyužil)

**Comment by luciajanikova** [comment]
Toto by sme tiez mohli uzavriet @jsuchal

**Comment by jsuchal** [comment]
@luciajanikova za mna toto je dobre, cize smelo ten wording tam dajme. Aj odkaz na tu el. sluzbu by som dal. PR k tomuto nie je, ze? Mozno by som to nechal ako komunitnu ulohu otvorene.

**Comment by luciajanikova** [comment]
PR som neotvorila, ale lokalne to mam. Tak pushnem, ked uz to je nachystane. Link na tú službu treba ak som spravne pochopila predchadzajucu konverzaciu pridat do navodu, hej? To mozeme niekomu prenechat na lepsi wording.

**Comment by luciajanikova** [comment]
Mozeme aj toto zatvorit po https://github.com/slovensko-digital/navody.digital/pull/582 @jsuchal?
