### ISSUE TITLE
Zlá lehota pre dopravný inšpektorát

### ISSUE THREAD

**Issue by TheEragon** [slovensko-digital/navody.digital#546]
Podľa [ministerstva vnútra](https://portal.minv.sk/wps/wcm/connect/sk/site/main/zivotne-situacie/vozidla/vozidla-evidencia-ziadosti/vozidla-ziadost-zmena-menu/) máme na nahlasénie zmeny TP 30 dní a nie 15 ako sa tvrdí v [návode](https://navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/poziadajte-o-zmenu-dopravny-inspektorat).

**Comment by jsuchal** [comment]
@HanaBene @PetraPlesnikova

**Comment by HanaBene** [comment]
opravene
