### ISSUE TITLE
Ladenie navodov

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#55]
Poznamky k navodom
zmena TP
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska
 - tu by bolo asi fajn napisat kedy sa tato situacia bezne deje
 - to prejdite na dalsi krok by som nedaval - to pridame vsade genericky cc @eronisko 
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/ohlaste-zmenu-trvaleho-pobytu
 - to rozbalovanie pri eid je zbytocne su tam schovane len dve slova.
 - suhlas vlastnika - mozno dat to nie ako rozbalovanie ale ako tip ze kedy to netreba. (neviem co je castejsi scenar) - dat to ako task (optional)
 - pamatam si ze tu bol nejaky problem ked ma clovek hypoteku (treba overit)
 - button prejst na hlasenie pobytu dat ako task s odkazom na sluzbu
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/vybavte-si-novy-obciansky-preukaz
 - pre vacsinu navodov je el. obciansky ako prerekvizita, neviem ci to chceme vsade opakovat.
 - cakacia lehota podobne ako to spravila ivet tu (https://staging.navody.digital/zivotne-situacie/aktivacia-eid)
 - ta otazka "dostali ste novy obciansky preukaz" by som dal ako task (mam novy OP) + predtym tiez ako task "poziadajte o vydanie noveho OP"
 - dalsi krok bude genericky - dat prec
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/dolezite-zmeny
 - toto je cisto informacny krok rozmyslam ci ho nevypustit uplne kedze je dalej.
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/obchodny-register
 - pozor dat do toho vykricnikoveho komponentu
 - opat dat ako task tu zmenu ORSR
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/poziadajte-o-zmenu-v-zivnostenskom-registri
 - toto je dost take uradnicke. nevieme vypustit ten legal talk?
 - prerekvizitu OP asi tiez prec
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/poziadajte-o-zmenu-dopravny-inspektorat
 - podobne ako vyssie
 - tu mozno treba spomenut co sa deje ked prechadzas medzi okresmi (nove znacky pokial viem) - toto treba doladit
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/poziadajte-o-zmenu-v-katasrti-nehnutelnosti
 - ten vzor urcite schovajme za rozbalovanie
- https://staging.navody.digital/zivotne-situacie/zmena-trvaleho-bydliska/krok/zmena-v-dalsich-organizaciach
 - toto rozbime na tasky alebo rovno na podkroky (neskor) (odkial mame tento zoznam? co sa posiela sudom/exekutorom napr?, danovy urad?, socialna poistovna?)

zivnost
- https://staging.navody.digital/zivotne-situacie/zalozenie-zivnosti/krok/zalozte-si-bankovy-ucet
 - "jeto vsak prakticke" - dajme ako standardny tip.
 - tie suvisiace odkazy mi tam nehraju - neviem uplne co s tym
- https://staging.navody.digital/zivotne-situacie/zalozenie-zivnosti/krok/ohlaste-svoju-zivnost
 - prerekvizity - eID je jasne, ale internet explorer a windows (!!!) tam treba dat vykricnikom (standardny komponent)
 - podulohy su divne
- https://staging.navody.digital/zivotne-situacie/zalozenie-zivnosti/krok/zaregistrojte-sa-na-dph
 - "Využite našu službu a zistite, či sa potebujete registrovať na DPH." -- hmm? kde?
- ocakaval by som posledny krok nieco v zmysle "co dalej" nejake tipy triky, ze co bude zivnostnik potrebovat (napriklad odvody do socialky, zdravotky, bude treba fakturacny softver...)

eiD
- https://staging.navody.digital/zivotne-situacie/aktivacia-eid
 -  v klude ako task dajme, ze mam obciansky s cipom a BOK
 - tu by mala byt nejaka rozbocka, ze co ak OP s BOK nemam, ze to musim ist vybavit osobne.
- https://staging.navody.digital/zivotne-situacie/aktivacia-eid/krok/certifikaty
 - toto je pravda len ak nemam OP s BOK. (co ale je pravda ze bude asi vacsina ludi)
 - ako task pridajme "uz to mam"
- https://staging.navody.digital/zivotne-situacie/aktivacia-eid/krok/instalacia
 - ako task pridajme instalaciu
 - tip presunme hore k instalacii ktorej sa tyka
- https://staging.navody.digital/zivotne-situacie/aktivacia-eid/krok/aktivacia
 - "Prihláste sa do slovensko.sk" -  
 - "Vykonajte aktiváciu" -> aktivujte si
 - "Ak si už raz aktivujete elektronickú schránku, štát Vám bude zasielať úradnú komunikáciu výhradne cez slovensko.sk" 
   posunme rovno pod nadpis "vykonajte aktivaciu"
 - tip - diskretny udaj - toto neviem preco je prave tu. 
- po ukonceni by som cakal nejake next steps - napriklad, ze teraz mozete vybavovat rozne zivotne situacie napr na navody.digital (odkaz na homepage)

**Comment by jsuchal** [comment]
strata dokladov
- https://staging.navody.digital/zivotne-situacie/strata-dokladov
  - ten vykricnik je nejako divne pozicovany (mal by byt v strede) cc @filiplikavcan 
  - toto je dobry kandidat na kontextovo senzitivne navody (kde si v rpvom kroku vyklikas co si stratil a potom uz ides)
  - vyhol by som sa odkazom na lave menu a tak (moze sa menit) skor dajme odkazy na na tie podkroky (nateraz)
- strata vodicskeho preukazu (toto znie skor ako ZS ako nejaky krok co mam urobit - napr nahlasenie straty VP), zvysne detto

**Comment by eronisko** [comment]
@HanaBene toto sa este riesi? Mozno by to bolo dobre rozbit do issues, inak sa to navzdy strati...

**Comment by HanaBene** [comment]
nie - tieto ulohy nedrzim v githube. zatvaram.
