### ISSUE TITLE
Pridat margin na /notifikacie

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#550]
https://navody.digital/notifikacie 
chyba margin nad prvym nadpisom, 
vzor napriklad v O projekte. 

tato stranka nie je z adminu, je to z kodu. asi?

**Comment by HanaBene** [comment]
Toto sme otvorili s UX timom, navrhnu jednotny manual pre texty na ND, potom impelementujeme.

**Comment by jsuchal** [comment]
Toto je podla mna dobre, ten velky margin davame len tam kde je vela textu.

**Comment by TomasMakan** [comment]
Súhlasím a zároveň nesúhlasím.
Pozerám marginy a sú rovnaké v obidvoch prípadoch:
Padding  (top, bottom) 40px na content bloku
Margin bottom 30px na nadpise

Rozdiel je v tom, že návod má Primárny nadpis Názov návodu so sivým pozadím a podnadpis ( základné informácie). A na informačných/technických stránkach tento sivý nadpis chýba.
![image](https://github.com/slovensko-digital/navody.digital/assets/53820969/db5ea5fc-faa8-4e30-be44-911e3929fb3e)

Celkové odsadenie po text je 120px

Ak chceme vizuálne zjednotiť všetky možnosti, tak potrebujeme k tým "beznázvovým" pridať blok s výškou 80px.

Čo sa úplne vymyká štandardu je:

- O projekte -  85 px, v 3 rôznych blokoch, každý má svoj padding (40, 30, 15)

**textová stránka bez krokovníka**
- Spojené voľby 2022 (treba schovať a zároveň je to v kategórii Bývanie) - 2x padding po 40 px, bez názvu
- elektronická komunikácia so štátom (https://navody.digital/elektronicka-komunikacia) - rovnaký princíp ako voľby

- Ak máme nejaký podnadpis (https://navody.digital/zivotne-situacie/zalozenie-zivnosti) 
- - Nadpis margin bottom  5px, podnadpis margin  bottom20px

- Žiadosť o kópiu listiny v zbierke listín obchodného registra (https://navody.digital/aplikacie/or-sr-listiny) - toto je nejaký hybrid. Snaží sa to byť štandardný návod, ale Nadpis je zlá veľkosť ( 48 miesto 36), nemá margin/padding
