### ISSUE TITLE
Ako pouzivatel ked dokoncim cele navod, chcem vidiet ze uz je vsetko hotovo

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#56]
Ked si pouzivatel vsetko odskrtne v ramci ZS tak by sa mu mala zobrazit nejaka stranka ze gratulujeme alebo nejaky znak ze vsetko prebehlo ako malo.

**Comment by eronisko** [comment]
Zatial taketo:
![image](https://user-images.githubusercontent.com/1374745/51644945-5ab42900-1f72-11e9-8f8c-4083ddc4b11f.png)
