### ISSUE TITLE
Hidden stav

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#563]
Ked robime release nejakeho navodu potrebujeme to preklikavat tak, aby to nikto moc nevidel. Chcelo by to nejaky hidden stav co to nebude zobrazovat vo vyhladavani, neda to do sidemapy... ale ked vies url tak to pojde.

**Comment by HanaBene** [comment]
Definovali sme spravanie navodov a appiek v jednotlivych stavoch takto: 
![stavy](https://user-images.githubusercontent.com/45393631/227712117-60e514f0-f900-41a6-9a51-29f8ac4d5bbf.png)
