### ISSUE TITLE
Linky na "o projekte", "hall of fame" atd vytiahnut do headera/footera

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#57]
@filiplikavcan @eronisko potrebujeme niekde dat linky na podstranky projektu

@HanaBene posle odkazy ktore tam treba pridat. obsah by mal byt ready.

**Comment by HanaBene** [comment]
https://staging.navody.digital/admin/pages tu je pripraveny text, Kto sme a O projekte

**Comment by eronisko** [comment]
Do Headra sa zmesti 1-2 linky, ale viac urcite nie.
BTW za mna by z kazdej tejto mohla byt aj FAQ

**Comment by HanaBene** [comment]
https://staging.navody.digital/kto-sme
https://staging.navody.digital/wall-of-fame
https://staging.navody.digital/contact-info

**Comment by HanaBene** [comment]
Toto pojde do footera, navrh mame od plat4m.

**Comment by jsuchal** [comment]
@eronisko Toto je hotovo nie?

**Comment by eronisko** [comment]
Áno
