### ISSUE TITLE
current topic component - bug

### ISSUE THREAD

**Issue by PetraPlesnikova** [slovensko-digital/navody.digital#583]
Na uvodnej stranke funguje preklik vpohode na navod, ktory sa linkuje.
Akonahle je clovek viac zanoreny v kategorii alebo v navode, uz preklik nefunguje: Stránka, ktorú hľadáte neexistuje

![image](https://user-images.githubusercontent.com/71546886/233342330-f0be3f62-b389-4b2c-b80e-a8b24b812f07.png)
![image](https://user-images.githubusercontent.com/71546886/233342449-0d6fbbd4-5d5d-4438-9674-44146ed3c258.png)

**Comment by jsuchal** [comment]
Chybalo tam /
