### ISSUE TITLE
update posledneho kroku v app parlamentne volby 2023

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#592]
Nazov kroku: 
Pošlite žiadosť na úrad

*p lead*
Na emailovú adresu obce (doplniť adresu ak je k dispozícii) odošlite nasledujúcu žiadosť: 
*textarea so žiadosťou*

*checkbox* 
Odoslal/a som žiadosť

*primary button*
Pokračovať

**Comment by HanaBene** [comment]
teraz ten krok vyzera takto: 
![Screenshot_35](https://github.com/slovensko-digital/navody.digital/assets/45393631/023e3290-0294-4d91-bab6-e3afe130257d)

**Comment by HanaBene** [comment]
prosim @celuchmarek zverejnis nam tu verziu kompletnu na stagingu? teraz tam je to osekane, co mame aj na prode. dakujem

**Comment by celuchmarek** [comment]
@HanaBene akými krokmi by som sa mal dostať na túto obrazovku, prosím?

**Comment by HanaBene** [comment]
Malo by to byt:
obcan -> ano, 
trvaly pobyt -> ano, 
miesto volby -> mimo trvaleho bydliska,
potom by si mal vyplnat formular a nasledne by tam malo byt, ze ako chces dorucit hlasovaci preukaz, dve rozne vetvy kde sa vyplna formular, podla toho ako sa dorucuju listky - ked sa ti dorucuje ziadost na adresu trvaleho bydliska, ked sa ti dorucuje ziadost na inu adresu a ked vyzdvihnuje listky ina osoba. 
Na konci tychto troch vetiev je tento krok, kedy posielas ziadost, ten treba upravit. 

Potom uz je len taka dakovna ci gratulacna page. Ale toto je z pamati, kedze to nemame klikatelne teraz 🤔

**Comment by celuchmarek** [comment]
@HanaBene Dal som to na staging https://staging.navody.digital/aplikacie/parlamentne-volby

**Comment by celuchmarek** [comment]
@HanaBene nahodil som na staging. Zatiaľ tam je napojený sheet z predošlých volieb.

**Comment by HanaBene** [comment]
@celuchmarek chyba teraz okno s textom emailu
![Screenshot 2023-08-17 084700](https://github.com/slovensko-digital/navody.digital/assets/45393631/bf731d3e-2466-4086-960f-2ac20fb9ea87)

**Comment by HanaBene** [comment]
vidim, ze ked kliknem na to skopirujte sa mi to zobrazi, ale toto pochybujem, ze ludia budu chapat. 
zaroven sme sa bavili s @jsuchal, ze otvaranie v emailovom klientovi ma nastavene minimum ludi. 
Teraz po kliknuti na skopirujte sa zobrazi dalsia veta s instrukciami, ktora je inou velkostou ako zvysok. 
![Screenshot 2023-08-17 084924](https://github.com/slovensko-digital/navody.digital/assets/45393631/12f5f84e-724e-436d-9e71-0f2640941ad4)


Dala by som k tomuto sync s Tajom.

**Comment by celuchmarek** [comment]
@HanaBene Updatol som to. To skrývanie by default bolo nakódene v starej verzii, tak som to pôvodne nemenil. Teraz som to vyhodil a pridal som aj samotnú emailovú adresu, keďže mailto je skôr nepoužívané.

![image](https://github.com/slovensko-digital/navody.digital/assets/12500066/9bdb8e9d-1898-4539-b268-e38793f4c596)

**Comment by HanaBene** [comment]
Tu je otvorena ta otazka emailoveho klienta, ideme cestou, ze nechavame aj tuto moznost, alebo zjedodusime text na: Skopírujte pripravený text žiadoti a odošlite na emailovú adresu obce: ...
cc @jsuchal

**Comment by jsuchal** [comment]
Ja by som to nechal pokial to nijako nezblbne flow.
