### ISSUE TITLE
Vyhľadávanie: Synonymá

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#6]
Mal by som vedieť indexovatelnym objektom (zs/procesny krok/otázka) pridat nejake keywords podla ktorych sa bude dat hladat. Typicky synonyma (zmena trvaleho pobytu, zmena bydliska, stahujem sa…)

Tieto by mali byt aj niekde v obsahu/metadatach aby to search engines zaindexovali.

**Comment by eronisko** [comment]
@jsuchal to co mame teraz (keywords) nam zatial nebude stacit?

**Comment by jsuchal** [comment]
Ano bude, len neviem ci sa to pouziva.

**Comment by eronisko** [comment]
Pouziva. Este pridam keywords do Pages a bude to eno nuno.

**Comment by eronisko** [comment]
Fixnute v efdad16736da68d95387b531ec644d7fdeb2e6ec
