### ISSUE TITLE
Private vulnerability reporting

### ISSUE THREAD

**Issue by Sim4n6** [slovensko-digital/navody.digital#628]
Hi,

I have identified a potential vulnerability in the latest codebase. could you please enable the Private Github Vulnerability reporting feature so that I can submit my report? 

https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

Thank you

**Comment by jsuchal** [comment]
https://github.com/slovensko-digital/navody.digital/security/advisories

**Comment by Sim4n6** [comment]
thank you very much, working on the report right away.

**Comment by Sim4n6** [comment]
@jsuchal report submitted at [GHSA-j568-22g5-q3xg](https://github.com/slovensko-digital/navody.digital/security/advisories/GHSA-j568-22g5-q3xg).

**Comment by Sim4n6** [comment]
Any update to consider about the matter, please?
