### ISSUE TITLE
na mobile nevie prehrat video na navodoch

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#633]
https://navody.digital/podpisovanie#ako-podpisat tato stranka na mobile vyzera takto a video nejde prehrat. 
![IMG_6038](https://github.com/slovensko-digital/navody.digital/assets/45393631/f300d131-2380-46d2-9b75-70db7e341287)

je to zariadenim, ci navodmi?
dakujem za riesenie

**Comment by jsuchal** [comment]
@HanaBene ake to je zariadenie / prehliadac? @alhafoudh @luciajanikova vy ste iphone - viete skusit?

**Comment by alhafoudh** [comment]
Ano, na iPhone to nejde. Tiez mam preskrtnuty play button.

**Comment by alhafoudh** [comment]
Toto je problem: `iPhone doesn't support WebM video playback natively`

**Comment by HanaBene** [comment]
dala som tam .mp4 video a to sa prehrava. @jsuchal ty vies tie dve videa co si robil konvertovat do mp4?

**Comment by jsuchal** [comment]
Podla mna to vie hocikto.

**Comment by jsuchal** [comment]
@HanaBene vieme toto doriesit?

**Comment by HanaBene** [comment]
tie formaty videa som zmenila, tak mozno este prosim jeden test iPhone ludia @luciajanikova @alhafoudh ak mozte a mozme zavriet.

**Comment by alhafoudh** [comment]
@HanaBene video v sekcii "Podpisovanie cez Autogram" je stale nefunkcne na iPhone. Ostatne videa v sekciach "Podpis s časovou pečiatkou" a "Overovanie podpisov cez Autogram" funguju.

**Comment by HanaBene** [comment]
tak skusila som este znova nahrat, ak teraz nepomohlo tak to budem musiet nechat na niekoho zdatnejsieho

**Comment by alhafoudh** [comment]
Stale to iste :(

**Comment by jsuchal** [comment]
@crutch toto vies kuknut?

**Comment by crutch** [comment]
Jedno z tych videi (podpisovanie cez Autogram) stale nejde na iphone/Safari. Nejde len toto prve, ostatne sa spustia v pohode.

**Comment by jsuchal** [comment]
Problem bol v kodeku. Fixnute.
