### ISSUE TITLE
Návod na vydanie certifikátov na eID

### ISSUE THREAD

**Issue by celuchmarek** [slovensko-digital/navody.digital#641]
Dobrý návod na vydanie certifikátov na OP nie je ani na stránke MV. Potrebujeme vyrobiť niečo veľmi zrozumiteľné, aby mohlo elektornický podpis používať viac ľudí.

**Comment by jsuchal** [comment]
hotovo https://navody.digital/zivotne-situacie/aktivacia-eid/krok/certifikaty
