### ISSUE TITLE
Eurovoľby 2024 - aplikácia voľby.digital

### ISSUE THREAD

**Issue by MirkaKosecova** [slovensko-digital/navody.digital#642]
Pripraviť aplikáciu na Európske voľby 2024

- Aktualizovať appku podľa prezidentských
- Zistiť termíny, pravidlá a doladiť texty
- Zbierať emaily samospráv!

**Comment by celuchmarek** [comment]
Možno relevantné info pre stručné intro v historickej issue #262

**Comment by TomasMakan** [comment]
Slack channel k voľby:
https://join.slack.com/share/enQtNzAyMjY2OTE3MzA3OC04YTE4ZTg1NTg3ZDM0ODk3ZDFhM2E0OGI3MjZlNWI1ZWE3YjRiNWYzOWY4ZDc2MzYxNmJkZWUyOWRmMWJiMWM5

**Comment by TomasMakan** [comment]
Postup:

-  vyhľadávam cez google: "obec Plášťovce okres levice voľby 2024"
- Ak neexistuje link priamo na voľby do EP, tak po otvorení stránky dávam ctrl+f a hľadám "voľby"
 Ak nenájdem odkaz cez browser vyhľadávanie, idem do menu. Niektoré obce to majú v sekcii Zverejňovanie, niektoré Samospráva. Tiež pozerám Novinky alebo Úradná tabuľa. 
 ak nenájdem ani tak, tak prezriem úvodnú stránku (v jednej šablóne používajú obce obrázok ako link a nemajú tam nastavené metadáta
 ak nepomôže ani toto, tak skúšam vyhľadávanie priamo na stránke

4 druhy formátov:
 pdf s mailto: linkou
 word s mailto: linkou
 pdf/ word ako text alebo pdf ako scan (obrázok) - tu len prepísať
 priamo na stránke ako text alebo mailto:

Väčšinou idem po okresoch doradu.

Chyby na ktoré som narazil:
 strašne zašitá stránka - trvalo 15 minút nájsť (často nemajú zverejnené dokumenty)
 majú zverejnenú iba jednu adresu - na delegovanie člena komisie. Tu predpokladám, že bude rovnaká ako na HP a dávam do tabuľky tú
 Majú zverejnenú iba časť dokumentov k voľbám (vyhlásenie volieb, info pre voličov) a delegovanie, volebná miestnosť, HP a pod. chýba
 Spájajú dokumenty do jedného/ viacerych súhrnných - treba potom prelustrovať, či tam sú aj maily
 pomenovanie súborov nehovorí nič o tom, aký je to súbor.

Tipujem, že cca. 5-10% obcí (hlavne tie malé) nezverejnia mail.
