### ISSUE TITLE
Nastylovat a prelozit google tlacitko na prihlasovanie

### ISSUE THREAD

**Issue by mirrec** [slovensko-digital/navody.digital#73]
https://developers.google.com/identity/branding-guidelines

Pre obrazovku prihlasovania ->
http://localhost:3000/session/new

**Comment by eronisko** [comment]
A idealne pouzit higher-res tlacidlo

**Comment by jsuchal** [comment]
@HanaBene toto rovno dajme do hackday milestone.

**Comment by smith558** [comment]
![google_btn](https://user-images.githubusercontent.com/44023416/62695411-92e2fc80-b9d6-11e9-8a58-42772a3ce786.png)
svg je tiez

**Comment by HanaBene** [comment]
@smith558 na portali vykame, dala by som tam Prihlasenie cez Google, Prihlaste sa s Google, Prihlasit cez Google, Prihlasit sa s Google. Nieco z toho. Ja som za Prihlasit cez Google

**Comment by smith558** [comment]
![google_btn](https://user-images.githubusercontent.com/44023416/62696036-e275f800-b9d7-11e9-93ff-bc62a6d1a208.png)

**Comment by smith558** [comment]
![image](https://user-images.githubusercontent.com/44023416/62699414-c0807380-b9df-11e9-9f4a-ff9c2ea1a96f.png)
![image](https://user-images.githubusercontent.com/44023416/62699427-c8d8ae80-b9df-11e9-9cba-c133f2f4583f.png)

**Comment by smith558** [comment]
Zatvaram
