### ISSUE TITLE
Search by mal fungovat lepsie

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#74]
Ked dam vyhladat "narodenie dietata blablabla" tak to nenajde nic aj ked match na prve dve slova. Google sa sprava inak. Ked nenajde ziadny vysledok alebo ich je malo, tak ponukne vysledky bez toho jedneho slova. 

cc @martyciz

**Comment by martyciz** [comment]
#89

**Comment by jsuchal** [comment]
Tuto mame nejaku grafiku 
![image](https://user-images.githubusercontent.com/26342/54741902-1df65e00-4bc0-11e9-8114-1f969fb052c9.png)

Plus skusme to takto https://github.com/slovensko-digital/navody.digital/pull/89#issuecomment-471781658

**Comment by jsuchal** [comment]
Toto @martyciz uz spravil, zatvaram.
