### ISSUE TITLE
action button - hotove podulohy

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#78]
pridat action button PODAT (alebo ine), ked mam hotove vsetky podkroky, ktory ma presmeruje na podanie, alebo vygneeruje nieco, ulozi atd = ukonci krok.

**Comment by jsuchal** [comment]
Toto je hotove, treba v adminovi nastavit na kroku `app_url` a typ na `ExternalAppStep`.

@HanaBene Vies upravit obsah tam kde je toto relevantne?

**Comment by HanaBene** [comment]
done, zatvaram
