### ISSUE TITLE
Newsletter: Ako používateľ sa chcem prihlásiť do newslettera

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#9]
Používame SendinBlue, integrácia je pomerne priamočiara, stačí skopírovať z našej stránky a vytvoriť nový list (aby emaily išli kam majú)

**Comment by alhafoudh** [comment]
@jsuchal kam budeme zbierat maily? vies toto rozhodnut? nasledne sa moze implementovat

**Comment by jsuchal** [comment]
@alhafoudh sendinblue by som nechal. Pozri ako to mame na slovensko.digital alebo na ekosystem.slovensko.digital spravene a tak to spravme.

**Comment by eronisko** [comment]
@jsuchal potrebujeme tu nakonfigurovat novy list na Sendinblue. Vies to spravit alebo mi dat access?

**Comment by jsuchal** [comment]
Inak Ivet ma pristup cize skus cez nu.

**Comment by eronisko** [comment]
Config je spraveny. API vracia result=success, ale nechodia mi ziadne potvrdzujuce spravy

**Comment by jsuchal** [comment]
@HanaBene nastavil som posielanie mailov na newsletter. Este treba poklikat ten flow:

1) Vidim tam bug ked uz niekto v zozname je (tvari sa, ze to neodoslalo).
2) Ivet ma pristup do sendinblue (manazment newslettra, treba upravit asi ten mail co pride) + mozno po prihlaseni redirect niekde k nam (dakovacka a co ma zmysel - mozno podpora) tu sa to nastavuje https://my.sendinblue.com/camp/template/91/message-setup + form je tu (https://my.sendinblue.com/advanced/signup-form/id/4)  mozno ma zmysel disclaimer presunut aj do emailu.

**Comment by HanaBene** [comment]
recap, chceme: 
- upravit design prihlasovacieho mailu - odklik na button v maily, ze sa naozaj hces prihlasit
- dakovacia/potvrdzovacia page - to sa v sendinblue robi? ci na navodoch?
- mesacne pripravovat newsletter - to budeme riesit s ivet, ano?
- prvy mail moze ist hned ako sa prihlasis, nieco ako sa portal pouziva?

**Comment by jsuchal** [comment]
1) To sa robi v sendinblue
2) Toto spravme na navodoch - a redirect sa nastavuje v SIB
3) ano
4) Ano to sa v SIB da tiez.

**Comment by HanaBene** [comment]
prihlasovaci mail som nechala simple, skoro ako bol
dakovacia page je https://navody.digital/newsletter
po prihlaseni pride welcome letter

doriesit unsubscribe, pripravila som form, este to tam treba nastavit, aby na tento to presmerovalo, nie na ten defaultny.

**Comment by jsuchal** [comment]
@HanaBene unsubscribe link je v kazdom emaili co SIB posiela (myslim), cize toto mozeme asi zavriet.
