### ISSUE TITLE
Mozem si rozkliknut viac menu naraz

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/navody.digital#90]
![image](https://user-images.githubusercontent.com/26342/52950738-5536dc80-3380-11e9-88b0-127bdda88913.png)
Ked kliknem na oznacit krok ako... tak by sa mali ostatne zavriet a nemalo by sa to dostat do tohto stavu.

**Comment by jsuchal** [comment]
cc @filiplikavcan

**Comment by filiplikavcan** [comment]
Toto uz je spravene, updatnite si assety.

S pozdravom,
Filip Likavčan

—
bratia.sk s.r.o.
+421 910 926 942

**Comment by jsuchal** [comment]
@filiplikavcan zda sa ze nie uplne.

**Comment by jsuchal** [comment]
Toto je fixnute.
