### ISSUE TITLE
ked zrusim checkbox (predtym oznaceny) z hotoveho kroku, krok sa nevrati do nedokonceneho - ostane hotovy.

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#95]

**Comment by tomas-radic** [comment]
Neviem ci ja mozem menit stav tychto issues, ale dal som pull request s riesenim tohto problemu. Po review/merge sa toto moze uzavriet.

**Comment by jsuchal** [comment]
@HanaBene vies overit ze toto funguje?

**Comment by HanaBene** [comment]
otestovane, zatvaram.
