### ISSUE TITLE
zafixovat headerline + button

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#97]

**Comment by jsuchal** [comment]
@filiplikavcan toto by mohlo byt celkom dobre riesenie. Skusil som dat headerline ako sticky a nie je to vobec zle. Skusil som zafixovat aj lave menu (tiez nie zle) ale ked je dlhe tak sa to sprava trochu divne pri skrolovani.

![image](https://user-images.githubusercontent.com/26342/52978786-0d8d7080-33d3-11e9-85ea-b05035ff44bd.png)

Co ty na to?

**Comment by jsuchal** [comment]
@filiplikavcan co ty na toto?

**Comment by jsuchal** [comment]
Toto je dnes uz skor bad practice.
