### ISSUE TITLE
search bar: po kliknuti nezmizne predvyplneny text

### ISSUE THREAD

**Issue by HanaBene** [slovensko-digital/navody.digital#98]

**Comment by martyciz** [comment]
Ahoj, mas na mysli text "Vyhladaj zivotnu situaciu"?
Lebo neviem to u seba reprodukovat (Chrome Version 72.0.3626.119), je to browser specific bug?

**Comment by HanaBene** [comment]
Ano, vyzera to byt fixnute, alebo specificke, takze to neviem momentalne zreprodukovat. Zatvaram, otvorim znova ak pridem na v akych podmienkach to bolo.
